R7FA4M2 Multi-Click Smartwatch: include/app_controller.h File Reference
app_controller.h File Reference
Application state-machine and foreground-loop interface.
#include <stdint.h>
Functions
int app_controller_init (void)
Initialize Click boards, sensors, display, BLE and interrupt sources.
void app_controller_run (void)
Run the cooperative foreground application loop indefinitely.
void app_controller_tick_1ms_isr (void)
Advance the system timebase and running stopwatch from the AGT0 ISR.
void app_controller_b3_button_isr (void)
Debounce the physical B3 input and queue its screen-cycle action.
void app_controller_b4_button_isr (void)
Debounce the physical B4 input and queue its stopwatch action.
void app_controller_request_dashboard_screen (void)
Request the BLE B1 action that opens the smartwatch dashboard.
void app_controller_request_environment_screen (void)
Request the BLE B2 action that opens the environment screen.
void app_controller_request_astronomy_screen (void)
Request the BLE B5 action that opens the Time of Day screen.
void app_controller_request_stopwatch_reset (void)
Request the BLE B3 action that stops and resets the stopwatch.
void app_controller_request_stopwatch_control (void)
Request the BLE B4 action that shows or toggles the stopwatch.
void app_controller_request_rtc_refresh (void)
Request a fresh RTC read and complete active-screen redraw.
uint32_t app_controller_get_system_ms (void)
Return the monotonic AGT0 application counter.
Detailed Description
Application state-machine and foreground-loop interface.
Definition in file app_controller.h.
Function Documentation
app_controller_b3_button_isr()
void app_controller_b3_button_isr (void)
Debounce the physical B3 input and queue its screen-cycle action.
Debounce the physical B3 input and queue its screen-cycle action.
Definition at line 84 of file app_controller.c.
References APP_B3_DEBOUNCE_MS, app_b3_last_press_ms, app_b3_seen, app_physical_b3_pending, and app_system_ms.
Referenced by P304_IRQ9_IRQHandler().
app_controller_b4_button_isr()
void app_controller_b4_button_isr (void)
Debounce the physical B4 input and queue its stopwatch action.
Debounce the physical B4 input and queue its stopwatch action.
Definition at line 99 of file app_controller.c.
References APP_B4_DEBOUNCE_MS, app_b4_last_press_ms, app_b4_seen, app_physical_b4_pending, and app_system_ms.
Referenced by P111_IRQ4_IRQHandler().
app_controller_get_system_ms()
uint32_t app_controller_get_system_ms (void)
Return the monotonic AGT0 application counter.
Returns
Milliseconds elapsed since the application tick was started.
Return the monotonic AGT0 application counter.
Returns
Result value.
Definition at line 60 of file app_controller.c.
References app_system_ms.
Referenced by bletiny_set_connected().
app_controller_init()
int app_controller_init (void)
Initialize Click boards, sensors, display, BLE and interrupt sources.
Returns
RTC14_OK on success; otherwise a negative application error code.
Initialize Click boards, sensors, display, BLE and interrupt sources.
Returns
Zero on success; otherwise a negative error code.
Definition at line 238 of file app_controller.c.
References APP_AUTO_B3_DEMO_ENABLED, app_auto_b3_last_trigger_ms, app_datetime, app_datetime_valid, app_environment, app_halt_with_error(), app_interrupts_init(), app_last_dashboard_render_ms, app_system_ms, bletiny_init(), temphum27_data_t::humidity_tenths_percent, ips2_init(), ips2_render_dashboard(), ips2_render_error(), system_clocks_t::pclka, system_clocks_t::pclkb, printf_me(), rtc14_get_datetime(), rtc14_init(), RTC14_OK, rtc14_print_datetime(), rtc14_set_default_datetime(), SYSTEM_GetClocksFrequency(), temphum27_data_t::temperature_tenths_c, temphum27_init(), temphum27_print_data(), temphum27_read_data(), and temphum27_data_t::valid.
Referenced by main().
app_controller_request_astronomy_screen()
void app_controller_request_astronomy_screen (void)
Request the BLE B5 action that opens the Time of Day screen.
Request the BLE B5 action that opens the Time of Day screen.
Definition at line 132 of file app_controller.c.
References app_ble_requested_screen, app_ble_screen_pending, and APP_SCREEN_ASTRONOMY.
Referenced by bletiny_process_stopwatch_command().
app_controller_request_dashboard_screen()
void app_controller_request_dashboard_screen (void)
Request the BLE B1 action that opens the smartwatch dashboard.
Request the BLE B1 action that opens the smartwatch dashboard.
Definition at line 114 of file app_controller.c.
References app_ble_requested_screen, app_ble_screen_pending, and APP_SCREEN_DASHBOARD.
Referenced by bletiny_process_stopwatch_command().
app_controller_request_environment_screen()
void app_controller_request_environment_screen (void)
Request the BLE B2 action that opens the environment screen.
Request the BLE B2 action that opens the environment screen.
Definition at line 123 of file app_controller.c.
References app_ble_requested_screen, app_ble_screen_pending, and APP_SCREEN_ENVIRONMENT.
Referenced by bletiny_process_stopwatch_command().
app_controller_request_rtc_refresh()
void app_controller_request_rtc_refresh (void)
Request a fresh RTC read and complete active-screen redraw.
Request a fresh RTC read and complete active-screen redraw.
Definition at line 157 of file app_controller.c.
References app_force_full_refresh, and app_periodic_update_pending.
Referenced by bletiny_process_rtc_command().
app_controller_request_stopwatch_control()
void app_controller_request_stopwatch_control (void)
Request the BLE B4 action that shows or toggles the stopwatch.
Request the BLE B4 action that shows or toggles the stopwatch.
Definition at line 149 of file app_controller.c.
References app_ble_stopwatch_control_pending.
Referenced by bletiny_process_stopwatch_command().
app_controller_request_stopwatch_reset()
void app_controller_request_stopwatch_reset (void)
Request the BLE B3 action that stops and resets the stopwatch.
Request the BLE B3 action that stops and resets the stopwatch.
Definition at line 141 of file app_controller.c.
References app_ble_stopwatch_reset_pending.
Referenced by bletiny_process_stopwatch_command().
app_controller_run()
void app_controller_run (void)
Run the cooperative foreground application loop indefinitely.
Run the cooperative foreground application loop indefinitely.
Definition at line 728 of file app_controller.c.
References app_handle_auto_b3(), app_handle_ble_screen_request(), app_handle_ble_status(), app_handle_ble_stopwatch_control(), app_handle_ble_stopwatch_reset(), app_handle_periodic_update(), app_handle_physical_b3(), app_handle_physical_b4(), app_refresh_active_screen_if_due(), app_system_ms, bletiny_process_rx(), and bletiny_service().
Referenced by main().
app_controller_tick_1ms_isr()
void app_controller_tick_1ms_isr (void)
Advance the system timebase and running stopwatch from the AGT0 ISR.
Advance the system timebase and running stopwatch from the AGT0 ISR.
Definition at line 68 of file app_controller.c.
References app_periodic_update_pending, app_stopwatch_ms, app_stopwatch_running, and app_system_ms.
Referenced by AGT0_IRQHandler().