R7FA4M2 Multi-Click Smartwatch: src/app_controller.c File Reference
app_controller.c File Reference
Application state machine and foreground scheduling.
#include "app_controller.h"
#include "app_config.h"
#include "app_interrupts.h"
#include "app_types.h"
#include "bletiny.h"
#include "ips2_display.h"
#include "project_platform.h"
#include "rtc14.h"
#include "temphum27.h"
Functions
static void app_halt_with_error (const char *message, int error)
Log a fatal initialization error and halt the processor.
uint32_t app_controller_get_system_ms (void)
Return the monotonic application timebase.
void app_controller_tick_1ms_isr (void)
Advance the system and stopwatch counters from the 1 ms tick ISR.
void app_controller_b3_button_isr (void)
Debounce B3 and queue the physical screen-cycle action.
void app_controller_b4_button_isr (void)
Debounce B4 and queue the physical stopwatch-control action.
void app_controller_request_dashboard_screen (void)
Queue dashboard screen.
void app_controller_request_environment_screen (void)
Queue environment screen.
void app_controller_request_astronomy_screen (void)
Queue astronomy screen.
void app_controller_request_stopwatch_reset (void)
Queue stopwatch reset.
void app_controller_request_stopwatch_control (void)
Queue stopwatch control.
void app_controller_request_rtc_refresh (void)
Queue rtc refresh.
static void app_reset_render_timers (void)
Invalidate all application-level display refresh timestamps.
static void app_render_active_screen (uint32_t now)
Render the currently selected application screen.
static void app_switch_screen (app_screen_t screen, uint32_t now)
Select a screen, invalidate display caches and render it immediately.
int app_controller_init (void)
Initialize the module.
static uint8_t app_handle_auto_b3 (uint32_t now)
Queue a physical B3 action when automatic demonstration mode expires.
static uint8_t app_handle_ble_status (void)
Refresh the UI after a BLE connection-state change.
static uint8_t app_handle_physical_b3 (uint32_t now)
Process a pending physical or automatic B3 action.
static uint8_t app_handle_physical_b4 (void)
Process a pending physical B4 stopwatch action.
static uint8_t app_handle_ble_screen_request (uint32_t now)
Apply a pending BLE screen-selection request.
static uint8_t app_handle_ble_stopwatch_reset (uint32_t now)
Apply the BLE stopwatch stop/reset request.
static uint8_t app_handle_ble_stopwatch_control (uint32_t now)
Apply the BLE stopwatch start/pause/continue request.
static uint8_t app_handle_periodic_update (uint32_t now)
Read the RTC and environmental sensor during the one-second update.
static uint8_t app_refresh_active_screen_if_due (uint32_t now)
Refresh animated screen content when its render interval expires.
void app_controller_run (void)
Handle run.
Variables
static volatile uint32_t app_system_ms
static volatile uint32_t app_stopwatch_ms
static volatile uint32_t app_b3_last_press_ms
static volatile uint32_t app_b4_last_press_ms
static volatile uint32_t app_auto_b3_last_trigger_ms
static volatile uint8_t app_b3_seen
static volatile uint8_t app_b4_seen
static volatile uint8_t app_stopwatch_running
static volatile uint8_t app_periodic_update_pending
static volatile uint8_t app_physical_b3_pending
static volatile uint8_t app_physical_b4_pending
static volatile uint8_t app_ble_screen_pending
static volatile app_screen_t app_ble_requested_screen
static volatile uint8_t app_ble_stopwatch_reset_pending
static volatile uint8_t app_ble_stopwatch_control_pending
static volatile uint8_t app_force_full_refresh
static volatile app_screen_t app_active_screen = APP_SCREEN_DASHBOARD
static rtc14_datetime_t app_datetime
static temphum27_data_t app_environment
static uint8_t app_datetime_valid
static uint32_t app_last_stopwatch_render_ms = 0xFFFFFFFFUL
static uint32_t app_last_dashboard_render_ms = 0xFFFFFFFFUL
static uint32_t app_last_environment_render_ms = 0xFFFFFFFFUL
static uint32_t app_last_astronomy_render_ms = 0xFFFFFFFFUL
Detailed Description
Application state machine and foreground scheduling.
Definition in file app_controller.c.
Function Documentation
app_controller_b3_button_isr()
void app_controller_b3_button_isr (void)
Debounce B3 and queue the physical screen-cycle action.
Debounce the physical B3 input and queue its screen-cycle action.
Definition at line 84 of file app_controller.c.
References APP_B3_DEBOUNCE_MS, app_b3_last_press_ms, app_b3_seen, app_physical_b3_pending, and app_system_ms.
Referenced by P304_IRQ9_IRQHandler().
app_controller_b4_button_isr()
void app_controller_b4_button_isr (void)
Debounce B4 and queue the physical stopwatch-control action.
Debounce the physical B4 input and queue its stopwatch action.
Definition at line 99 of file app_controller.c.
References APP_B4_DEBOUNCE_MS, app_b4_last_press_ms, app_b4_seen, app_physical_b4_pending, and app_system_ms.
Referenced by P111_IRQ4_IRQHandler().
app_controller_get_system_ms()
uint32_t app_controller_get_system_ms (void)
Return the monotonic application timebase.
Return the monotonic AGT0 application counter.
Returns
Result value.
Definition at line 60 of file app_controller.c.
References app_system_ms.
Referenced by bletiny_set_connected().
app_controller_init()
int app_controller_init (void)
Initialize the module.
Initialize Click boards, sensors, display, BLE and interrupt sources.
Returns
Zero on success; otherwise a negative error code.
Definition at line 238 of file app_controller.c.
References APP_AUTO_B3_DEMO_ENABLED, app_auto_b3_last_trigger_ms, app_datetime, app_datetime_valid, app_environment, app_halt_with_error(), app_interrupts_init(), app_last_dashboard_render_ms, app_system_ms, bletiny_init(), temphum27_data_t::humidity_tenths_percent, ips2_init(), ips2_render_dashboard(), ips2_render_error(), system_clocks_t::pclka, system_clocks_t::pclkb, printf_me(), rtc14_get_datetime(), rtc14_init(), RTC14_OK, rtc14_print_datetime(), rtc14_set_default_datetime(), SYSTEM_GetClocksFrequency(), temphum27_data_t::temperature_tenths_c, temphum27_init(), temphum27_print_data(), temphum27_read_data(), and temphum27_data_t::valid.
Referenced by main().
app_controller_request_astronomy_screen()
void app_controller_request_astronomy_screen (void)
Queue astronomy screen.
Request the BLE B5 action that opens the Time of Day screen.
Definition at line 132 of file app_controller.c.
References app_ble_requested_screen, app_ble_screen_pending, and APP_SCREEN_ASTRONOMY.
Referenced by bletiny_process_stopwatch_command().
app_controller_request_dashboard_screen()
void app_controller_request_dashboard_screen (void)
Queue dashboard screen.
Request the BLE B1 action that opens the smartwatch dashboard.
Definition at line 114 of file app_controller.c.
References app_ble_requested_screen, app_ble_screen_pending, and APP_SCREEN_DASHBOARD.
Referenced by bletiny_process_stopwatch_command().
app_controller_request_environment_screen()
void app_controller_request_environment_screen (void)
Queue environment screen.
Request the BLE B2 action that opens the environment screen.
Definition at line 123 of file app_controller.c.
References app_ble_requested_screen, app_ble_screen_pending, and APP_SCREEN_ENVIRONMENT.
Referenced by bletiny_process_stopwatch_command().
app_controller_request_rtc_refresh()
void app_controller_request_rtc_refresh (void)
Queue rtc refresh.
Request a fresh RTC read and complete active-screen redraw.
Definition at line 157 of file app_controller.c.
References app_force_full_refresh, and app_periodic_update_pending.
Referenced by bletiny_process_rtc_command().
app_controller_request_stopwatch_control()
void app_controller_request_stopwatch_control (void)
Queue stopwatch control.
Request the BLE B4 action that shows or toggles the stopwatch.
Definition at line 149 of file app_controller.c.
References app_ble_stopwatch_control_pending.
Referenced by bletiny_process_stopwatch_command().
app_controller_request_stopwatch_reset()
void app_controller_request_stopwatch_reset (void)
Queue stopwatch reset.
Request the BLE B3 action that stops and resets the stopwatch.
Definition at line 141 of file app_controller.c.
References app_ble_stopwatch_reset_pending.
Referenced by bletiny_process_stopwatch_command().
app_controller_run()
void app_controller_run (void)
Handle run.
Run the cooperative foreground application loop indefinitely.
Definition at line 728 of file app_controller.c.
References app_handle_auto_b3(), app_handle_ble_screen_request(), app_handle_ble_status(), app_handle_ble_stopwatch_control(), app_handle_ble_stopwatch_reset(), app_handle_periodic_update(), app_handle_physical_b3(), app_handle_physical_b4(), app_refresh_active_screen_if_due(), app_system_ms, bletiny_process_rx(), and bletiny_service().
Referenced by main().
app_controller_tick_1ms_isr()
void app_controller_tick_1ms_isr (void)
Advance the system and stopwatch counters from the 1 ms tick ISR.
Advance the system timebase and running stopwatch from the AGT0 ISR.
Definition at line 68 of file app_controller.c.
References app_periodic_update_pending, app_stopwatch_ms, app_stopwatch_running, and app_system_ms.
Referenced by AGT0_IRQHandler().
app_halt_with_error()
static void app_halt_with_error (const char * message, int error) static
Log a fatal initialization error and halt the processor.
Parameters
[in] message Printf-compatible fatal error message.
[in] error Error code appended to the log message.
Definition at line 47 of file app_controller.c.
References printf_me().
Referenced by app_controller_init().
app_handle_auto_b3()
static uint8_t app_handle_auto_b3 (uint32_t now) static
Queue a physical B3 action when automatic demonstration mode expires.
Parameters
[in] now Current monotonic application time in milliseconds.
Returns
Nonzero when the requested work succeeds or changes state; otherwise zero.
Definition at line 337 of file app_controller.c.
References APP_AUTO_B3_DEMO_ENABLED, APP_AUTO_B3_DEMO_INTERVAL_MS, app_auto_b3_last_trigger_ms, and app_physical_b3_pending.
Referenced by app_controller_run().
app_handle_ble_screen_request()
static uint8_t app_handle_ble_screen_request (uint32_t now) static
Apply a pending BLE screen-selection request.
Parameters
[in] now Current monotonic application time in milliseconds.
Returns
Nonzero when the requested work succeeds or changes state; otherwise zero.
Definition at line 476 of file app_controller.c.
References app_ble_requested_screen, app_ble_screen_pending, and app_switch_screen().
Referenced by app_controller_run().
app_handle_ble_status()
static uint8_t app_handle_ble_status (void) static
Refresh the UI after a BLE connection-state change.
Returns
Nonzero when the requested work succeeds or changes state; otherwise zero.
Definition at line 355 of file app_controller.c.
References app_active_screen, bletiny_take_connection_changed(), ips2_render_ble_status(), and printf_me().
Referenced by app_controller_run().
app_handle_ble_stopwatch_control()
static uint8_t app_handle_ble_stopwatch_control (uint32_t now) static
Apply the BLE stopwatch start/pause/continue request.
Parameters
[in] now Current monotonic application time in milliseconds.
Returns
Nonzero when the requested work succeeds or changes state; otherwise zero.
Definition at line 533 of file app_controller.c.
References app_active_screen, app_ble_stopwatch_control_pending, app_last_stopwatch_render_ms, app_reset_render_timers(), APP_SCREEN_STOPWATCH, app_stopwatch_ms, app_stopwatch_running, bletiny_is_connected(), ips2_invalidate_screen(), and ips2_render_timer().
Referenced by app_controller_run().
app_handle_ble_stopwatch_reset()
static uint8_t app_handle_ble_stopwatch_reset (uint32_t now) static
Apply the BLE stopwatch stop/reset request.
Parameters
[in] now Current monotonic application time in milliseconds.
Returns
Nonzero when the requested work succeeds or changes state; otherwise zero.
Definition at line 504 of file app_controller.c.
References app_ble_stopwatch_reset_pending, APP_SCREEN_STOPWATCH, app_stopwatch_ms, app_stopwatch_running, and app_switch_screen().
Referenced by app_controller_run().
app_handle_periodic_update()
static uint8_t app_handle_periodic_update (uint32_t now) static
Read the RTC and environmental sensor during the one-second update.
Parameters
[in] now Current monotonic application time in milliseconds.
Returns
Nonzero when the requested work succeeds or changes state; otherwise zero.
Definition at line 574 of file app_controller.c.
References app_active_screen, app_datetime, app_datetime_valid, app_environment, app_force_full_refresh, app_last_astronomy_render_ms, app_last_dashboard_render_ms, app_last_environment_render_ms, app_periodic_update_pending, app_reset_render_timers(), APP_SCREEN_ASTRONOMY, APP_SCREEN_DASHBOARD, APP_SCREEN_ENVIRONMENT, bletiny_is_connected(), ips2_invalidate_screen(), ips2_render_astronomy(), ips2_render_dashboard(), ips2_render_environment(), ips2_render_error(), printf_me(), rtc14_get_datetime(), RTC14_OK, rtc14_print_datetime(), temphum27_print_data(), and temphum27_read_data().
Referenced by app_controller_run().
app_handle_physical_b3()
static uint8_t app_handle_physical_b3 (uint32_t now) static
Process a pending physical or automatic B3 action.
Parameters
[in] now Current monotonic application time in milliseconds.
Returns
Nonzero when the requested work succeeds or changes state; otherwise zero.
Definition at line 373 of file app_controller.c.
References app_active_screen, app_auto_b3_last_trigger_ms, app_last_stopwatch_render_ms, app_physical_b3_pending, APP_SCREEN_ASTRONOMY, APP_SCREEN_DASHBOARD, APP_SCREEN_ENVIRONMENT, APP_SCREEN_STOPWATCH, app_stopwatch_ms, app_stopwatch_running, app_switch_screen(), bletiny_is_connected(), and ips2_render_timer().
Referenced by app_controller_run().
app_handle_physical_b4()
static uint8_t app_handle_physical_b4 (void) static
Process a pending physical B4 stopwatch action.
Returns
Nonzero when the requested work succeeds or changes state; otherwise zero.
Definition at line 436 of file app_controller.c.
References app_active_screen, app_last_stopwatch_render_ms, app_physical_b4_pending, APP_SCREEN_STOPWATCH, app_stopwatch_ms, app_stopwatch_running, bletiny_is_connected(), and ips2_render_timer().
Referenced by app_controller_run().
app_refresh_active_screen_if_due()
static uint8_t app_refresh_active_screen_if_due (uint32_t now) static
Refresh animated screen content when its render interval expires.
Parameters
[in] now Current monotonic application time in milliseconds.
Returns
Result value.
Definition at line 652 of file app_controller.c.
References app_active_screen, app_datetime, app_datetime_valid, app_environment, app_last_astronomy_render_ms, app_last_dashboard_render_ms, app_last_environment_render_ms, app_last_stopwatch_render_ms, APP_SCREEN_DASHBOARD, APP_SCREEN_ENVIRONMENT, APP_SCREEN_STOPWATCH, app_stopwatch_ms, app_stopwatch_running, bletiny_is_connected(), IPS2_ASTRONOMY_REFRESH_MS, IPS2_DASHBOARD_REFRESH_MS, IPS2_ENVIRONMENT_REFRESH_MS, ips2_render_astronomy(), ips2_render_dashboard(), ips2_render_environment(), ips2_render_error(), ips2_render_timer(), and IPS2_STOPWATCH_REFRESH_MS.
Referenced by app_controller_run().
app_render_active_screen()
static void app_render_active_screen (uint32_t now) static
Render the currently selected application screen.
Parameters
[in] now Current monotonic application time in milliseconds.
Definition at line 178 of file app_controller.c.
References app_active_screen, app_datetime, app_datetime_valid, app_environment, app_last_astronomy_render_ms, app_last_dashboard_render_ms, app_last_environment_render_ms, app_last_stopwatch_render_ms, APP_SCREEN_ASTRONOMY, APP_SCREEN_DASHBOARD, APP_SCREEN_ENVIRONMENT, app_stopwatch_ms, app_stopwatch_running, bletiny_is_connected(), ips2_render_astronomy(), ips2_render_dashboard(), ips2_render_environment(), ips2_render_error(), and ips2_render_timer().
Referenced by app_switch_screen().
app_reset_render_timers()
static void app_reset_render_timers (void) static
Invalidate all application-level display refresh timestamps.
Definition at line 166 of file app_controller.c.
References app_last_astronomy_render_ms, app_last_dashboard_render_ms, app_last_environment_render_ms, and app_last_stopwatch_render_ms.
Referenced by app_handle_ble_stopwatch_control(), app_handle_periodic_update(), and app_switch_screen().
app_switch_screen()
static void app_switch_screen (app_screen_t screen, uint32_t now) static
Select a screen, invalidate display caches and render it immediately.
Parameters
[in] screen Application screen whose status area is being updated.
[in] now Current monotonic application time in milliseconds.
Definition at line 223 of file app_controller.c.
References app_active_screen, app_render_active_screen(), app_reset_render_timers(), and ips2_invalidate_screen().
Referenced by app_handle_ble_screen_request(), app_handle_ble_stopwatch_reset(), and app_handle_physical_b3().
Variable Documentation
app_active_screen
volatile app_screen_t app_active_screen = APP_SCREEN_DASHBOARD static
Definition at line 32 of file app_controller.c.
Referenced by app_handle_ble_status(), app_handle_ble_stopwatch_control(), app_handle_periodic_update(), app_handle_physical_b3(), app_handle_physical_b4(), app_refresh_active_screen_if_due(), app_render_active_screen(), and app_switch_screen().
app_auto_b3_last_trigger_ms
volatile uint32_t app_auto_b3_last_trigger_ms static
Definition at line 20 of file app_controller.c.
Referenced by app_controller_init(), app_handle_auto_b3(), and app_handle_physical_b3().
app_b3_last_press_ms
volatile uint32_t app_b3_last_press_ms static
Definition at line 18 of file app_controller.c.
Referenced by app_controller_b3_button_isr().
app_b3_seen
volatile uint8_t app_b3_seen static
Definition at line 21 of file app_controller.c.
Referenced by app_controller_b3_button_isr().
app_b4_last_press_ms
volatile uint32_t app_b4_last_press_ms static
Definition at line 19 of file app_controller.c.
Referenced by app_controller_b4_button_isr().
app_b4_seen
volatile uint8_t app_b4_seen static
Definition at line 22 of file app_controller.c.
Referenced by app_controller_b4_button_isr().
app_ble_requested_screen
volatile app_screen_t app_ble_requested_screen static
Definition at line 28 of file app_controller.c.
Referenced by app_controller_request_astronomy_screen(), app_controller_request_dashboard_screen(), app_controller_request_environment_screen(), and app_handle_ble_screen_request().
app_ble_screen_pending
volatile uint8_t app_ble_screen_pending static
Definition at line 27 of file app_controller.c.
Referenced by app_controller_request_astronomy_screen(), app_controller_request_dashboard_screen(), app_controller_request_environment_screen(), and app_handle_ble_screen_request().
app_ble_stopwatch_control_pending
volatile uint8_t app_ble_stopwatch_control_pending static
Definition at line 30 of file app_controller.c.
Referenced by app_controller_request_stopwatch_control(), and app_handle_ble_stopwatch_control().
app_ble_stopwatch_reset_pending
volatile uint8_t app_ble_stopwatch_reset_pending static
Definition at line 29 of file app_controller.c.
Referenced by app_controller_request_stopwatch_reset(), and app_handle_ble_stopwatch_reset().
app_datetime
rtc14_datetime_t app_datetime static
Definition at line 34 of file app_controller.c.
Referenced by app_controller_init(), app_handle_periodic_update(), app_refresh_active_screen_if_due(), and app_render_active_screen().
app_datetime_valid
uint8_t app_datetime_valid static
Definition at line 36 of file app_controller.c.
Referenced by app_controller_init(), app_handle_periodic_update(), app_refresh_active_screen_if_due(), and app_render_active_screen().
app_environment
temphum27_data_t app_environment static
Definition at line 35 of file app_controller.c.
Referenced by app_controller_init(), app_handle_periodic_update(), app_refresh_active_screen_if_due(), and app_render_active_screen().
app_force_full_refresh
volatile uint8_t app_force_full_refresh static
Definition at line 31 of file app_controller.c.
Referenced by app_controller_request_rtc_refresh(), and app_handle_periodic_update().
app_last_astronomy_render_ms
uint32_t app_last_astronomy_render_ms = 0xFFFFFFFFUL static
Definition at line 40 of file app_controller.c.
Referenced by app_handle_periodic_update(), app_refresh_active_screen_if_due(), app_render_active_screen(), and app_reset_render_timers().
app_last_dashboard_render_ms
uint32_t app_last_dashboard_render_ms = 0xFFFFFFFFUL static
Definition at line 38 of file app_controller.c.
Referenced by app_controller_init(), app_handle_periodic_update(), app_refresh_active_screen_if_due(), app_render_active_screen(), and app_reset_render_timers().
app_last_environment_render_ms
uint32_t app_last_environment_render_ms = 0xFFFFFFFFUL static
Definition at line 39 of file app_controller.c.
Referenced by app_handle_periodic_update(), app_refresh_active_screen_if_due(), app_render_active_screen(), and app_reset_render_timers().
app_last_stopwatch_render_ms
uint32_t app_last_stopwatch_render_ms = 0xFFFFFFFFUL static
Definition at line 37 of file app_controller.c.
Referenced by app_handle_ble_stopwatch_control(), app_handle_physical_b3(), app_handle_physical_b4(), app_refresh_active_screen_if_due(), app_render_active_screen(), and app_reset_render_timers().
app_periodic_update_pending
volatile uint8_t app_periodic_update_pending static
Definition at line 24 of file app_controller.c.
Referenced by app_controller_request_rtc_refresh(), app_controller_tick_1ms_isr(), and app_handle_periodic_update().
app_physical_b3_pending
volatile uint8_t app_physical_b3_pending static
Definition at line 25 of file app_controller.c.
Referenced by app_controller_b3_button_isr(), app_handle_auto_b3(), and app_handle_physical_b3().
app_physical_b4_pending
volatile uint8_t app_physical_b4_pending static
Definition at line 26 of file app_controller.c.
Referenced by app_controller_b4_button_isr(), and app_handle_physical_b4().
app_stopwatch_ms
volatile uint32_t app_stopwatch_ms static
Definition at line 17 of file app_controller.c.
Referenced by app_controller_tick_1ms_isr(), app_handle_ble_stopwatch_control(), app_handle_ble_stopwatch_reset(), app_handle_physical_b3(), app_handle_physical_b4(), app_refresh_active_screen_if_due(), and app_render_active_screen().
app_stopwatch_running
volatile uint8_t app_stopwatch_running static
Definition at line 23 of file app_controller.c.
Referenced by app_controller_tick_1ms_isr(), app_handle_ble_stopwatch_control(), app_handle_ble_stopwatch_reset(), app_handle_physical_b3(), app_handle_physical_b4(), app_refresh_active_screen_if_due(), and app_render_active_screen().
app_system_ms
volatile uint32_t app_system_ms static
Definition at line 16 of file app_controller.c.
Referenced by app_controller_b3_button_isr(), app_controller_b4_button_isr(), app_controller_get_system_ms(), app_controller_init(), app_controller_run(), and app_controller_tick_1ms_isr().