R7FA4M2 Multi-Click Smartwatch: include/app_interrupts.h File Reference
app_interrupts.h File Reference
Interrupt-vector, AGT0 tick and physical-button interface.
#include <stdint.h>
Functions
int app_interrupts_init (uint32_t pclkb_hz)
Install RAM vectors and initialize AGT0, IRQ9 and IRQ4.
void AGT0_IRQHandler (void)
AGT0 1 ms underflow interrupt handler.
void P304_IRQ9_IRQHandler (void)
P304 / IRQ9 B3 interrupt handler.
void P111_IRQ4_IRQHandler (void)
P111 / IRQ4 B4 interrupt handler.
Detailed Description
Interrupt-vector, AGT0 tick and physical-button interface.
Definition in file app_interrupts.h.
Function Documentation
AGT0_IRQHandler()
void AGT0_IRQHandler (void)
AGT0 1 ms underflow interrupt handler.
AGT0 1 ms underflow interrupt handler.
Definition at line 240 of file app_interrupts.c.
References ra4m2_agt16_registers_t::AGTCR, APP_AGT0_IRQ_SLOT, app_controller_tick_1ms_isr(), and rtc14_agt0_registers().
Referenced by rtc14_install_interrupt_vectors().
app_interrupts_init()
int app_interrupts_init (uint32_t pclkb_hz)
Install RAM vectors and initialize AGT0, IRQ9 and IRQ4.
Parameters
[in] pclkb_hz Peripheral clock B frequency in hertz.
Returns
RTC14_OK on success; otherwise a negative application error code.
Install RAM vectors and initialize AGT0, IRQ9 and IRQ4.
Parameters
[in] pclkb_hz Peripheral clock B frequency in hertz.
Returns
Zero on success; otherwise a negative error code.
Definition at line 276 of file app_interrupts.c.
References rtc14_agt0_init(), rtc14_install_interrupt_vectors(), RTC14_OK, rtc14_p111_irq_init(), and rtc14_p304_irq_init().
Referenced by app_controller_init().
P111_IRQ4_IRQHandler()
void P111_IRQ4_IRQHandler (void)
P111 / IRQ4 B4 interrupt handler.
P111 / IRQ4 B4 interrupt handler.
Definition at line 264 of file app_interrupts.c.
References APP_B4_IRQ_SLOT, and app_controller_b4_button_isr().
Referenced by rtc14_install_interrupt_vectors().
P304_IRQ9_IRQHandler()
void P304_IRQ9_IRQHandler (void)
P304 / IRQ9 B3 interrupt handler.
P304 / IRQ9 B3 interrupt handler.
Definition at line 254 of file app_interrupts.c.
References APP_B3_IRQ_SLOT, and app_controller_b3_button_isr().
Referenced by rtc14_install_interrupt_vectors().