R7FA4M2 Multi-Click Smartwatch: src/app_interrupts.c File Reference
app_interrupts.c File Reference
RAM vector installation, AGT0 tick and external button IRQ routing.
#include "app_interrupts.h"
#include "app_config.h"
#include "app_controller.h"
#include "app_types.h"
#include "bletiny.h"
#include "ra4m2_baremetal.h"
Functions
static uintptr_t app_ram_vector_table[APP_VECTOR_COUNT] __attribute__ ((aligned(256)))
static volatile ra4m2_agt16_registers_t * rtc14_agt0_registers (void)
Return the AGT0 register view used by the application tick driver.
static void rtc14_install_interrupt_vectors (void)
Copy the vector table to RAM and install application handlers.
static int rtc14_agt0_select_1ms_clock (uint32_t pclkb_hz, uint8_t *agtmr1, uint16_t *reload)
Choose an AGT0 divider and reload value for a 1 ms period.
static int rtc14_agt0_init (uint32_t pclkb_hz)
Configure AGT0 as the 1 ms application timebase.
static void rtc14_p304_irq_init (void)
Configure P304/IRQ9 as the falling-edge B3 input.
static void rtc14_p111_irq_init (void)
Configure P111/IRQ4 as the falling-edge B4 input.
void AGT0_IRQHandler (void)
Handle an AGT0 underflow and advance the 1 ms application tick.
void P304_IRQ9_IRQHandler (void)
Acknowledge IRQ9 and queue the B3 action.
void P111_IRQ4_IRQHandler (void)
Acknowledge IRQ4 and queue the B4 action.
int app_interrupts_init (uint32_t pclkb_hz)
Handle interrupts init.
Detailed Description
RAM vector installation, AGT0 tick and external button IRQ routing.
Definition in file app_interrupts.c.
Function Documentation
__attribute__()
static uintptr_t app_ram_vector_table[APP_VECTOR_COUNT] __attribute__ ((aligned(256))) static
AGT0_IRQHandler()
void AGT0_IRQHandler (void)
Handle an AGT0 underflow and advance the 1 ms application tick.
AGT0 1 ms underflow interrupt handler.
Definition at line 240 of file app_interrupts.c.
References ra4m2_agt16_registers_t::AGTCR, APP_AGT0_IRQ_SLOT, app_controller_tick_1ms_isr(), and rtc14_agt0_registers().
Referenced by rtc14_install_interrupt_vectors().
app_interrupts_init()
int app_interrupts_init (uint32_t pclkb_hz)
Handle interrupts init.
Install RAM vectors and initialize AGT0, IRQ9 and IRQ4.
Parameters
[in] pclkb_hz Peripheral clock B frequency in hertz.
Returns
Zero on success; otherwise a negative error code.
Definition at line 276 of file app_interrupts.c.
References rtc14_agt0_init(), rtc14_install_interrupt_vectors(), RTC14_OK, rtc14_p111_irq_init(), and rtc14_p304_irq_init().
Referenced by app_controller_init().
P111_IRQ4_IRQHandler()
void P111_IRQ4_IRQHandler (void)
Acknowledge IRQ4 and queue the B4 action.
P111 / IRQ4 B4 interrupt handler.
Definition at line 264 of file app_interrupts.c.
References APP_B4_IRQ_SLOT, and app_controller_b4_button_isr().
Referenced by rtc14_install_interrupt_vectors().
P304_IRQ9_IRQHandler()
void P304_IRQ9_IRQHandler (void)
Acknowledge IRQ9 and queue the B3 action.
P304 / IRQ9 B3 interrupt handler.
Definition at line 254 of file app_interrupts.c.
References APP_B3_IRQ_SLOT, and app_controller_b3_button_isr().
Referenced by rtc14_install_interrupt_vectors().
rtc14_agt0_init()
static int rtc14_agt0_init (uint32_t pclkb_hz) static
Configure AGT0 as the 1 ms application timebase.
Parameters
[in] pclkb_hz Peripheral clock B frequency in hertz.
Returns
Zero on success; otherwise a negative error code.
Definition at line 116 of file app_interrupts.c.
References ra4m2_agt16_registers_t::AGT, AGT0_MSTPCRD_BIT, AGT_AGTCR_START_TIMER, AGT_AGTCR_TCSTF, ra4m2_agt16_registers_t::AGTCMA, ra4m2_agt16_registers_t::AGTCMB, ra4m2_agt16_registers_t::AGTCMSR, ra4m2_agt16_registers_t::AGTCR, ra4m2_agt16_registers_t::AGTIOC, ra4m2_agt16_registers_t::AGTIOSEL, ra4m2_agt16_registers_t::AGTISR, ra4m2_agt16_registers_t::AGTMR1, ra4m2_agt16_registers_t::AGTMR2, APP_AGT0_EVENT, APP_AGT0_IRQ_PRIORITY, APP_AGT0_IRQ_SLOT, APP_I2C_TIMEOUT, rtc14_agt0_registers(), rtc14_agt0_select_1ms_clock(), RTC14_ERROR_TIMEOUT, and RTC14_OK.
Referenced by app_interrupts_init().
rtc14_agt0_registers()
static volatile ra4m2_agt16_registers_t * rtc14_agt0_registers (void) static
Return the AGT0 register view used by the application tick driver.
Returns
Pointer to the requested register or data view.
Definition at line 23 of file app_interrupts.c.
Referenced by AGT0_IRQHandler(), and rtc14_agt0_init().
rtc14_agt0_select_1ms_clock()
static int rtc14_agt0_select_1ms_clock (uint32_t pclkb_hz, uint8_t * agtmr1, uint16_t * reload) static
Choose an AGT0 divider and reload value for a 1 ms period.
Parameters
[in] pclkb_hz Peripheral clock B frequency in hertz.
[in] agtmr1 Agtmr1 value.
[in] reload Reload value.
Returns
Calculated or converted value.
Definition at line 75 of file app_interrupts.c.
References AGT_AGTMR1_TCK_PCLKB_DIV_1, AGT_AGTMR1_TCK_PCLKB_DIV_2, AGT_AGTMR1_TCK_PCLKB_DIV_8, APP_AGT0_TICK_HZ, RTC14_ERROR_ARGUMENT, RTC14_ERROR_CLOCK, and RTC14_OK.
Referenced by rtc14_agt0_init().
rtc14_install_interrupt_vectors()
static void rtc14_install_interrupt_vectors (void) static
Copy the vector table to RAM and install application handlers.
Definition at line 32 of file app_interrupts.c.
References AGT0_IRQHandler(), APP_AGT0_IRQ_SLOT, APP_B3_IRQ_SLOT, APP_B4_IRQ_SLOT, APP_CORE_VECTOR_COUNT, APP_VECTOR_COUNT, BLETINY_SCI3_ERI_IRQ_SLOT, BLETINY_SCI3_ERI_IRQHandler(), BLETINY_SCI3_RX_IRQ_SLOT, BLETINY_SCI3_RXI_IRQHandler(), P111_IRQ4_IRQHandler(), and P304_IRQ9_IRQHandler().
Referenced by app_interrupts_init().
rtc14_p111_irq_init()
static void rtc14_p111_irq_init (void) static
Configure P111/IRQ4 as the falling-edge B4 input.
Definition at line 212 of file app_interrupts.c.
References APP_B4_IRQ_CHANNEL, APP_B4_IRQ_EVENT, APP_B4_IRQ_PRIORITY, APP_B4_IRQ_SLOT, ICU_IRQCR_FALLING_EDGE, PFS_ISEL_IRQ, and PFS_PCR_PULLUP.
Referenced by app_interrupts_init().
rtc14_p304_irq_init()
static void rtc14_p304_irq_init (void) static
Configure P304/IRQ9 as the falling-edge B3 input.
Definition at line 184 of file app_interrupts.c.
References APP_B3_IRQ_CHANNEL, APP_B3_IRQ_EVENT, APP_B3_IRQ_PRIORITY, APP_B3_IRQ_SLOT, ICU_IRQCR_FALLING_EDGE, PFS_ISEL_IRQ, and PFS_PCR_PULLUP.
Referenced by app_interrupts_init().