R7FA4M2 Multi-Click Smartwatch: src/bletiny.c File Reference
bletiny.c File Reference
BLE TINY CodeLess UART transport, connection tracking and remote commands.
#include "bletiny.h"
#include "app_config.h"
#include "app_controller.h"
#include "app_types.h"
#include "ra4m2_baremetal.h"
#include "rtc14.h"
Macros
#define BLETINY_RST_MASK (1U << 11) /* P211 */
Functions
static volatile ra4m2_sci_registers_t * bletiny_sci3 (void)
Return the SCI3 register view used by BLE Tiny Click.
static void bletiny_rst_high (void)
Deassert the BLE Tiny hardware reset signal.
static void bletiny_rst_low (void)
Assert the BLE Tiny hardware reset signal.
static void bletiny_configure_pins (void)
Configure pins.
static int bletiny_sci3_set_baud (uint32_t pclka_hz, uint32_t baud_hz)
Select SCI3 baud-rate settings closest to the requested rate.
static void bletiny_uart_write_byte (uint8_t value)
Transmit one byte through SCI3.
static void bletiny_uart_write_text (const char *text)
Transmit a null-terminated command string through SCI3.
static void bletiny_send_command (const char *command)
Send a CodeLess command terminated with carriage return.
static void bletiny_rx_push (uint8_t value)
Append one received byte to the interrupt-safe ring buffer.
static int bletiny_rx_pop (uint8_t *value)
Remove one byte from the receive ring buffer.
static uint8_t bletiny_line_contains (const char *line, const char *token)
Test whether a received response line contains a token.
static uint8_t bletiny_find_token (const char *line, const char *token, uint16_t *token_index)
Locate a token inside a received response line.
static uint8_t bletiny_parse_uint_field (const char **cursor, uint32_t *value, uint8_t expect_separator)
Parse one unsigned decimal field from a command payload.
static uint8_t bletiny_process_rtc_command (const char *line)
Validate and apply an RTC command received through CodeLess memory.
static uint8_t bletiny_process_stopwatch_command (const char *line)
Decode BLE screen and stopwatch trigger commands.
static void bletiny_set_connected (uint8_t connected)
Update the cached BLE connection state and change flag.
static void bletiny_process_line (const char *line)
Parse one complete SCI3 response line.
uint8_t bletiny_process_rx (void)
Process rx.
int bletiny_init (uint32_t pclka_hz, uint32_t now_ms)
Initialize the module.
void BLETINY_SCI3_RXI_IRQHandler (void)
Store a received SCI3 byte in the BLE ring buffer.
void BLETINY_SCI3_ERI_IRQHandler (void)
Clear SCI3 receive errors and preserve any pending byte.
uint8_t bletiny_is_connected (void)
Determine whether connected.
uint8_t bletiny_take_connection_changed (uint8_t *connected)
Consume connection changed.
uint8_t bletiny_service (uint32_t now_ms)
Service periodic module work.
Variables
static volatile uint8_t bletiny_rx_buffer [BLETINY_RX_BUFFER_SIZE]
static volatile uint16_t bletiny_rx_head
static volatile uint16_t bletiny_rx_tail
static volatile uint8_t bletiny_rx_overflow
static volatile uint8_t bletiny_connected
static volatile uint8_t bletiny_status_dirty = 1U
static uint32_t bletiny_next_status_query_ms
static uint32_t bletiny_next_mem_query_ms
static char bletiny_line_buffer [BLETINY_LINE_BUFFER_SIZE]
static uint16_t bletiny_line_length
Detailed Description
BLE TINY CodeLess UART transport, connection tracking and remote commands.
Definition in file bletiny.c.
Macro Definition Documentation
BLETINY_RST_MASK
#define BLETINY_RST_MASK (1U << 11) /* P211 */
Definition at line 25 of file bletiny.c.
Function Documentation
bletiny_configure_pins()
static void bletiny_configure_pins (void) static
Configure pins.
Definition at line 56 of file bletiny.c.
References PFS_PDR_OUTPUT, PFS_PMR_PERIPHERAL, PFS_PODR_HIGH, and PFS_PSEL.
Referenced by bletiny_init().
bletiny_find_token()
static uint8_t bletiny_find_token (const char * line, const char * token, uint16_t * token_index) static
Locate a token inside a received response line.
Parameters
[in] line Null-terminated received response line.
[in] token Token to locate or match.
[in] token_index Token index value.
Returns
Result value.
Definition at line 326 of file bletiny.c.
Referenced by bletiny_process_rtc_command(), and bletiny_process_stopwatch_command().
bletiny_init()
int bletiny_init (uint32_t pclka_hz, uint32_t now_ms)
Initialize the module.
Initialize BLE Tiny Click over SCI3 UART.
Parameters
[in] pclka_hz Peripheral clock A frequency in hertz.
[in] now_ms Current monotonic application time in milliseconds.
Returns
Zero on success; otherwise a negative error code.
Definition at line 703 of file bletiny.c.
References bletiny_configure_pins(), bletiny_connected, BLETINY_MEM_QUERY_MS, bletiny_next_mem_query_ms, bletiny_next_status_query_ms, bletiny_rst_high(), bletiny_rst_low(), bletiny_sci3(), BLETINY_SCI3_ERI_EVENT, BLETINY_SCI3_ERI_IRQ_SLOT, BLETINY_SCI3_IRQ_PRIORITY, BLETINY_SCI3_RX_EVENT, BLETINY_SCI3_RX_IRQ_SLOT, bletiny_sci3_set_baud(), bletiny_send_command(), bletiny_status_dirty, BLETINY_STATUS_QUERY_MS, BLETINY_UART_BAUD, ra4m2_sci_registers_t::fcr, SCI_FCR_FM, SCI_SCMR_CHR1, SCI_SCMR_SDIR, SCI_SCMR_SINV, SCI_SCMR_SMIF, SCI_SCR_RE, SCI_SCR_RIE, SCI_SCR_TE, SCI_SIMR1_IICM, SCI_SMR_CHR, SCI_SMR_CM, SCI_SMR_PE, SCI_SMR_PM, SCI_SMR_STOP, SCI_SSR_FER, SCI_SSR_ORER, SCI_SSR_PER, ra4m2_sci_registers_t::scmr, ra4m2_sci_registers_t::scr, ra4m2_sci_registers_t::semr, ra4m2_sci_registers_t::simr1, ra4m2_sci_registers_t::smr, ra4m2_sci_registers_t::snfr, ra4m2_sci_registers_t::spmr, and ra4m2_sci_registers_t::ssr.
Referenced by app_controller_init().
bletiny_is_connected()
uint8_t bletiny_is_connected (void)
Determine whether connected.
Return the current BLE connection state.
Returns
Result value.
Definition at line 822 of file bletiny.c.
References bletiny_connected.
Referenced by app_handle_ble_stopwatch_control(), app_handle_periodic_update(), app_handle_physical_b3(), app_handle_physical_b4(), app_refresh_active_screen_if_due(), and app_render_active_screen().
bletiny_line_contains()
static uint8_t bletiny_line_contains (const char * line, const char * token) static
Test whether a received response line contains a token.
Parameters
[in] line Null-terminated received response line.
[in] token Token to locate or match.
Returns
Nonzero when the requested work succeeds or changes state; otherwise zero.
Definition at line 285 of file bletiny.c.
Referenced by bletiny_process_line().
bletiny_parse_uint_field()
static uint8_t bletiny_parse_uint_field (const char ** cursor, uint32_t * value, uint8_t expect_separator) static
Parse one unsigned decimal field from a command payload.
Parameters
[in] cursor Current parser position.
[in] value Value to process.
[in] expect_separator Expect separator value.
Returns
Nonzero when the requested work succeeds or changes state; otherwise zero.
Definition at line 370 of file bletiny.c.
Referenced by bletiny_process_rtc_command().
bletiny_process_line()
static void bletiny_process_line (const char * line) static
Parse one complete SCI3 response line.
Parameters
[in] line Null-terminated received response line.
Definition at line 600 of file bletiny.c.
References bletiny_line_contains(), bletiny_process_rtc_command(), bletiny_process_stopwatch_command(), and bletiny_set_connected().
Referenced by bletiny_process_rx().
bletiny_process_rtc_command()
static uint8_t bletiny_process_rtc_command (const char * line) static
Validate and apply an RTC command received through CodeLess memory.
Parameters
[in] line Null-terminated received response line.
Returns
Result value.
Definition at line 424 of file bletiny.c.
References app_controller_request_rtc_refresh(), bletiny_find_token(), bletiny_parse_uint_field(), bletiny_send_command(), printf_me(), RTC14_ERROR_ARGUMENT, RTC14_OK, and rtc14_set_datetime_24h().
Referenced by bletiny_process_line().
bletiny_process_rx()
uint8_t bletiny_process_rx (void)
Process rx.
Parse all bytes currently stored by the SCI3 receive interrupt.
Returns
Nonzero when the requested work succeeds or changes state; otherwise zero.
Definition at line 648 of file bletiny.c.
References bletiny_line_buffer, BLETINY_LINE_BUFFER_SIZE, bletiny_line_length, bletiny_process_line(), bletiny_rx_head, bletiny_rx_overflow, bletiny_rx_pop(), bletiny_rx_tail, and printf_me().
Referenced by app_controller_run().
bletiny_process_stopwatch_command()
static uint8_t bletiny_process_stopwatch_command (const char * line) static
Decode BLE screen and stopwatch trigger commands.
Parameters
[in] line Null-terminated received response line.
Returns
Result value.
Definition at line 508 of file bletiny.c.
References app_controller_request_astronomy_screen(), app_controller_request_dashboard_screen(), app_controller_request_environment_screen(), app_controller_request_stopwatch_control(), app_controller_request_stopwatch_reset(), bletiny_find_token(), bletiny_send_command(), and printf_me().
Referenced by bletiny_process_line().
bletiny_rst_high()
static void bletiny_rst_high (void) static
Deassert the BLE Tiny hardware reset signal.
Definition at line 40 of file bletiny.c.
References BLETINY_RST_MASK.
Referenced by bletiny_init().
bletiny_rst_low()
static void bletiny_rst_low (void) static
Assert the BLE Tiny hardware reset signal.
Definition at line 48 of file bletiny.c.
References BLETINY_RST_MASK.
Referenced by bletiny_init().
bletiny_rx_pop()
static int bletiny_rx_pop (uint8_t * value) static
Remove one byte from the receive ring buffer.
Parameters
[in] value Value to process.
Returns
Nonzero when the requested work succeeds or changes state; otherwise zero.
Definition at line 247 of file bletiny.c.
References bletiny_rx_buffer, BLETINY_RX_BUFFER_SIZE, bletiny_rx_head, and bletiny_rx_tail.
Referenced by bletiny_process_rx().
bletiny_rx_push()
static void bletiny_rx_push (uint8_t value) static
Append one received byte to the interrupt-safe ring buffer.
Parameters
[in] value Value to process.
Definition at line 226 of file bletiny.c.
References bletiny_rx_buffer, BLETINY_RX_BUFFER_SIZE, bletiny_rx_head, bletiny_rx_overflow, and bletiny_rx_tail.
Referenced by BLETINY_SCI3_ERI_IRQHandler(), and BLETINY_SCI3_RXI_IRQHandler().
bletiny_sci3()
static volatile ra4m2_sci_registers_t * bletiny_sci3 (void) static
Return the SCI3 register view used by BLE Tiny Click.
Returns
Pointer to the requested register or data view.
Definition at line 32 of file bletiny.c.
Referenced by bletiny_init(), BLETINY_SCI3_ERI_IRQHandler(), BLETINY_SCI3_RXI_IRQHandler(), bletiny_sci3_set_baud(), bletiny_send_command(), bletiny_uart_write_byte(), and bletiny_uart_write_text().
BLETINY_SCI3_ERI_IRQHandler()
void BLETINY_SCI3_ERI_IRQHandler (void)
Clear SCI3 receive errors and preserve any pending byte.
SCI3 receive-error interrupt handler.
Definition at line 804 of file bletiny.c.
References bletiny_rx_push(), bletiny_sci3(), BLETINY_SCI3_ERI_IRQ_SLOT, ra4m2_sci_registers_t::rdr, SCI_SSR_FER, SCI_SSR_ORER, SCI_SSR_PER, SCI_SSR_RDRF, and ra4m2_sci_registers_t::ssr.
Referenced by rtc14_install_interrupt_vectors().
BLETINY_SCI3_RXI_IRQHandler()
void BLETINY_SCI3_RXI_IRQHandler (void)
Store a received SCI3 byte in the BLE ring buffer.
SCI3 receive-data interrupt handler.
Definition at line 792 of file bletiny.c.
References bletiny_rx_push(), bletiny_sci3(), BLETINY_SCI3_RX_IRQ_SLOT, and ra4m2_sci_registers_t::rdr.
Referenced by rtc14_install_interrupt_vectors().
bletiny_sci3_set_baud()
static int bletiny_sci3_set_baud (uint32_t pclka_hz, uint32_t baud_hz) static
Select SCI3 baud-rate settings closest to the requested rate.
Parameters
[in] pclka_hz Peripheral clock A frequency in hertz.
[in] baud_hz Baud hz value.
Returns
Zero on success; otherwise a negative error code.
Definition at line 82 of file bletiny.c.
References bletiny_sci3(), ra4m2_sci_registers_t::brr, SCI_SEMR_ABCS, SCI_SEMR_ABCSE, SCI_SEMR_BGDM, SCI_SEMR_BRME, ra4m2_sci_registers_t::semr, and ra4m2_sci_registers_t::smr.
Referenced by bletiny_init().
bletiny_send_command()
static void bletiny_send_command (const char * command) static
Send a CodeLess command terminated with carriage return.
Parameters
[in] command CodeLess or display command string/value.
Definition at line 212 of file bletiny.c.
References bletiny_sci3(), bletiny_uart_write_byte(), bletiny_uart_write_text(), and SCI_SSR_TEND.
Referenced by bletiny_init(), bletiny_process_rtc_command(), bletiny_process_stopwatch_command(), and bletiny_service().
bletiny_service()
uint8_t bletiny_service (uint32_t now_ms)
Service periodic module work.
Run periodic GAP-status and CodeLess-memory polling.
Parameters
[in] now_ms Current monotonic application time in milliseconds.
Returns
Nonzero when the requested work succeeds or changes state; otherwise zero.
Definition at line 858 of file bletiny.c.
References bletiny_connected, BLETINY_MEM_QUERY_MS, bletiny_next_mem_query_ms, bletiny_next_status_query_ms, bletiny_send_command(), and BLETINY_STATUS_QUERY_MS.
Referenced by app_controller_run().
bletiny_set_connected()
static void bletiny_set_connected (uint8_t connected) static
Update the cached BLE connection state and change flag.
Parameters
[in] connected BLE connection state or destination for that state.
Definition at line 579 of file bletiny.c.
References app_controller_get_system_ms(), bletiny_connected, BLETINY_MEM_FIRST_QUERY_MS, bletiny_next_mem_query_ms, and bletiny_status_dirty.
Referenced by bletiny_process_line().
bletiny_take_connection_changed()
uint8_t bletiny_take_connection_changed (uint8_t * connected)
Consume connection changed.
Consume a pending BLE connection-state change.
Parameters
[out] connected BLE connection state or destination for that state.
Returns
Nonzero when the requested work succeeds or changes state; otherwise zero.
Definition at line 832 of file bletiny.c.
References bletiny_connected, and bletiny_status_dirty.
Referenced by app_handle_ble_status().
bletiny_uart_write_byte()
static void bletiny_uart_write_byte (uint8_t value) static
Transmit one byte through SCI3.
Parameters
[in] value Value to process.
Definition at line 181 of file bletiny.c.
References bletiny_sci3(), SCI_SSR_TDRE, ra4m2_sci_registers_t::ssr, and ra4m2_sci_registers_t::tdr.
Referenced by bletiny_send_command(), and bletiny_uart_write_text().
bletiny_uart_write_text()
static void bletiny_uart_write_text (const char * text) static
Transmit a null-terminated command string through SCI3.
Parameters
[in] text Null-terminated text string.
Definition at line 195 of file bletiny.c.
References bletiny_sci3(), bletiny_uart_write_byte(), and SCI_SSR_TEND.
Referenced by bletiny_send_command().
Variable Documentation
bletiny_connected
volatile uint8_t bletiny_connected static
Definition at line 18 of file bletiny.c.
Referenced by bletiny_init(), bletiny_is_connected(), bletiny_service(), bletiny_set_connected(), and bletiny_take_connection_changed().
bletiny_line_buffer
char bletiny_line_buffer[BLETINY_LINE_BUFFER_SIZE] static
Definition at line 22 of file bletiny.c.
Referenced by bletiny_process_rx().
bletiny_line_length
uint16_t bletiny_line_length static
Definition at line 23 of file bletiny.c.
Referenced by bletiny_process_rx().
bletiny_next_mem_query_ms
uint32_t bletiny_next_mem_query_ms static
Definition at line 21 of file bletiny.c.
Referenced by bletiny_init(), bletiny_service(), and bletiny_set_connected().
bletiny_next_status_query_ms
uint32_t bletiny_next_status_query_ms static
Definition at line 20 of file bletiny.c.
Referenced by bletiny_init(), and bletiny_service().
bletiny_rx_buffer
volatile uint8_t bletiny_rx_buffer[BLETINY_RX_BUFFER_SIZE] static
Definition at line 14 of file bletiny.c.
Referenced by bletiny_rx_pop(), and bletiny_rx_push().
bletiny_rx_head
volatile uint16_t bletiny_rx_head static
Definition at line 15 of file bletiny.c.
Referenced by bletiny_process_rx(), bletiny_rx_pop(), and bletiny_rx_push().
bletiny_rx_overflow
volatile uint8_t bletiny_rx_overflow static
Definition at line 17 of file bletiny.c.
Referenced by bletiny_process_rx(), and bletiny_rx_push().
bletiny_rx_tail
volatile uint16_t bletiny_rx_tail static
Definition at line 16 of file bletiny.c.
Referenced by bletiny_process_rx(), bletiny_rx_pop(), and bletiny_rx_push().
bletiny_status_dirty
volatile uint8_t bletiny_status_dirty = 1U static
Definition at line 19 of file bletiny.c.
Referenced by bletiny_init(), bletiny_set_connected(), and bletiny_take_connection_changed().