R7FA4M2 Multi-Click Smartwatch: include/bletiny.h File Reference
bletiny.h File Reference
BLE Tiny Click SCI3 and CodeLess command interface.
#include <stdint.h>
Functions
int bletiny_init (uint32_t pclka_hz, uint32_t now_ms)
Initialize BLE Tiny Click over SCI3 UART.
uint8_t bletiny_process_rx (void)
Parse all bytes currently stored by the SCI3 receive interrupt.
uint8_t bletiny_service (uint32_t now_ms)
Run periodic GAP-status and CodeLess-memory polling.
uint8_t bletiny_is_connected (void)
Return the current BLE connection state.
uint8_t bletiny_take_connection_changed (uint8_t *connected)
Consume a pending BLE connection-state change.
void BLETINY_SCI3_RXI_IRQHandler (void)
SCI3 receive-data interrupt handler.
void BLETINY_SCI3_ERI_IRQHandler (void)
SCI3 receive-error interrupt handler.
Detailed Description
BLE Tiny Click SCI3 and CodeLess command interface.
Definition in file bletiny.h.
Function Documentation
bletiny_init()
int bletiny_init (uint32_t pclka_hz, uint32_t now_ms)
Initialize BLE Tiny Click over SCI3 UART.
Parameters
[in] pclka_hz Peripheral clock A frequency in hertz.
[in] now_ms Current application time in milliseconds.
Returns
Zero on success; otherwise a negative error code.
Initialize BLE Tiny Click over SCI3 UART.
Parameters
[in] pclka_hz Peripheral clock A frequency in hertz.
[in] now_ms Current monotonic application time in milliseconds.
Returns
Zero on success; otherwise a negative error code.
Definition at line 703 of file bletiny.c.
References bletiny_configure_pins(), bletiny_connected, BLETINY_MEM_QUERY_MS, bletiny_next_mem_query_ms, bletiny_next_status_query_ms, bletiny_rst_high(), bletiny_rst_low(), bletiny_sci3(), BLETINY_SCI3_ERI_EVENT, BLETINY_SCI3_ERI_IRQ_SLOT, BLETINY_SCI3_IRQ_PRIORITY, BLETINY_SCI3_RX_EVENT, BLETINY_SCI3_RX_IRQ_SLOT, bletiny_sci3_set_baud(), bletiny_send_command(), bletiny_status_dirty, BLETINY_STATUS_QUERY_MS, BLETINY_UART_BAUD, ra4m2_sci_registers_t::fcr, SCI_FCR_FM, SCI_SCMR_CHR1, SCI_SCMR_SDIR, SCI_SCMR_SINV, SCI_SCMR_SMIF, SCI_SCR_RE, SCI_SCR_RIE, SCI_SCR_TE, SCI_SIMR1_IICM, SCI_SMR_CHR, SCI_SMR_CM, SCI_SMR_PE, SCI_SMR_PM, SCI_SMR_STOP, SCI_SSR_FER, SCI_SSR_ORER, SCI_SSR_PER, ra4m2_sci_registers_t::scmr, ra4m2_sci_registers_t::scr, ra4m2_sci_registers_t::semr, ra4m2_sci_registers_t::simr1, ra4m2_sci_registers_t::smr, ra4m2_sci_registers_t::snfr, ra4m2_sci_registers_t::spmr, and ra4m2_sci_registers_t::ssr.
Referenced by app_controller_init().
bletiny_is_connected()
uint8_t bletiny_is_connected (void)
Return the current BLE connection state.
Returns
Nonzero while connected; otherwise zero.
Return the current BLE connection state.
Returns
Result value.
Definition at line 822 of file bletiny.c.
References bletiny_connected.
Referenced by app_handle_ble_stopwatch_control(), app_handle_periodic_update(), app_handle_physical_b3(), app_handle_physical_b4(), app_refresh_active_screen_if_due(), and app_render_active_screen().
bletiny_process_rx()
uint8_t bletiny_process_rx (void)
Parse all bytes currently stored by the SCI3 receive interrupt.
Returns
Nonzero when at least one complete response line was processed.
Parse all bytes currently stored by the SCI3 receive interrupt.
Returns
Nonzero when the requested work succeeds or changes state; otherwise zero.
Definition at line 648 of file bletiny.c.
References bletiny_line_buffer, BLETINY_LINE_BUFFER_SIZE, bletiny_line_length, bletiny_process_line(), bletiny_rx_head, bletiny_rx_overflow, bletiny_rx_pop(), bletiny_rx_tail, and printf_me().
Referenced by app_controller_run().
BLETINY_SCI3_ERI_IRQHandler()
void BLETINY_SCI3_ERI_IRQHandler (void)
SCI3 receive-error interrupt handler.
SCI3 receive-error interrupt handler.
Definition at line 804 of file bletiny.c.
References bletiny_rx_push(), bletiny_sci3(), BLETINY_SCI3_ERI_IRQ_SLOT, ra4m2_sci_registers_t::rdr, SCI_SSR_FER, SCI_SSR_ORER, SCI_SSR_PER, SCI_SSR_RDRF, and ra4m2_sci_registers_t::ssr.
Referenced by rtc14_install_interrupt_vectors().
BLETINY_SCI3_RXI_IRQHandler()
void BLETINY_SCI3_RXI_IRQHandler (void)
SCI3 receive-data interrupt handler.
SCI3 receive-data interrupt handler.
Definition at line 792 of file bletiny.c.
References bletiny_rx_push(), bletiny_sci3(), BLETINY_SCI3_RX_IRQ_SLOT, and ra4m2_sci_registers_t::rdr.
Referenced by rtc14_install_interrupt_vectors().
bletiny_service()
uint8_t bletiny_service (uint32_t now_ms)
Run periodic GAP-status and CodeLess-memory polling.
Parameters
[in] now_ms Current application time in milliseconds.
Returns
Nonzero when a command was transmitted or processed.
Run periodic GAP-status and CodeLess-memory polling.
Parameters
[in] now_ms Current monotonic application time in milliseconds.
Returns
Nonzero when the requested work succeeds or changes state; otherwise zero.
Definition at line 858 of file bletiny.c.
References bletiny_connected, BLETINY_MEM_QUERY_MS, bletiny_next_mem_query_ms, bletiny_next_status_query_ms, bletiny_send_command(), and BLETINY_STATUS_QUERY_MS.
Referenced by app_controller_run().
bletiny_take_connection_changed()
uint8_t bletiny_take_connection_changed (uint8_t * connected)
Consume a pending BLE connection-state change.
Parameters
[out] connected Destination for the latest connection state.
Returns
Nonzero when a pending state change was consumed.
Consume a pending BLE connection-state change.
Parameters
[out] connected BLE connection state or destination for that state.
Returns
Nonzero when the requested work succeeds or changes state; otherwise zero.
Definition at line 832 of file bletiny.c.
References bletiny_connected, and bletiny_status_dirty.
Referenced by app_handle_ble_status().