R7FA4M2 Multi-Click Smartwatch: src/iic0_bus.c File Reference
iic0_bus.c File Reference
Polling IIC0 master transport shared by RTC 14 and Temp&Hum 27.
#include "iic0_bus.h"
#include "app_config.h"
#include "app_types.h"
#include "ra4m2_baremetal.h"
Functions
static int iic0_wait_set (volatile uint8_t *reg, uint8_t mask)
Wait until all requested register bits become set.
static int iic0_wait_clear (volatile uint8_t *reg, uint8_t mask)
Wait until all requested register bits become clear.
static int iic0_wait_transmit_flag (uint8_t mask)
Wait for the next IIC transmit-ready or completion flag.
static void iic0_set_receive_nack (uint8_t nack)
Configure the ACK/NACK response used for the next received byte.
static void iic0_clear_receive_state (void)
Clear receive flags before starting an IIC read phase.
static int iic0_request_stop (void)
Generate an IIC STOP condition and wait for bus release.
static void iic0_configure_pins (void)
Configure pins.
static int iic0_configure_bitrate (uint32_t pclkb_hz, uint32_t bitrate_hz)
Calculate and apply IIC0 clock timing registers.
int iic0_bus_init (void)
Handle bus init.
int iic0_bus_write (uint8_t address, const uint8_t *data, uint32_t length, uint8_t restart_after_write)
Handle bus write.
int iic0_bus_read_after_restart (uint8_t address, uint8_t *data, uint32_t length)
Read bytes after a repeated START generated by the write phase.
Detailed Description
Polling IIC0 master transport shared by RTC 14 and Temp&Hum 27.
Definition in file iic0_bus.c.
Function Documentation
iic0_bus_init()
int iic0_bus_init (void)
Handle bus init.
Initialize IIC0 on P400/P401 at the configured bus speed.
Returns
Zero on success; otherwise a negative error code.
Definition at line 256 of file iic0_bus.c.
References APP_I2C_BITRATE_HZ, iic0_clear_receive_state(), iic0_configure_bitrate(), iic0_configure_pins(), IIC_ICCR1_ICE, IIC_ICCR1_IICRST, system_clocks_t::pclkb, RTC14_OK, and SYSTEM_GetClocksFrequency().
Referenced by rtc14_init().
iic0_bus_read_after_restart()
int iic0_bus_read_after_restart (uint8_t address, uint8_t * data, uint32_t length)
Read bytes after a repeated START generated by the write phase.
Parameters
[in] address 7-bit I2C device address.
[out] data Data buffer.
[in] length Number of bytes in the buffer.
Returns
Zero on success; otherwise a negative error code.
Definition at line 369 of file iic0_bus.c.
References iic0_clear_receive_state(), iic0_set_receive_nack(), iic0_wait_clear(), iic0_wait_set(), IIC_ICCR2_RS, IIC_ICCR2_SP, IIC_ICCR2_TRS, IIC_ICMR3_WAIT, IIC_ICSR2_NACKF, IIC_ICSR2_RDRF, IIC_ICSR2_STOP, RTC14_ERROR_ARGUMENT, RTC14_ERROR_NACK, and RTC14_OK.
Referenced by rtc14_read_registers(), and temphum27_read_data().
iic0_bus_write()
int iic0_bus_write (uint8_t address, const uint8_t * data, uint32_t length, uint8_t restart_after_write)
Handle bus write.
Write one transaction to a 7-bit I2C address.
Parameters
[in] address 7-bit I2C device address.
[in] data Data buffer.
[in] length Number of bytes in the buffer.
[in] restart_after_write Nonzero to leave the bus in repeated-START state.
Returns
Zero on success; otherwise a negative error code.
Definition at line 299 of file iic0_bus.c.
References iic0_request_stop(), iic0_wait_clear(), iic0_wait_set(), iic0_wait_transmit_flag(), IIC_ICCR2_BBSY, IIC_ICCR2_RS, IIC_ICCR2_ST, IIC_ICSR2_NACKF, IIC_ICSR2_STOP, IIC_ICSR2_TDRE, IIC_ICSR2_TEND, RTC14_ERROR_ARGUMENT, and RTC14_OK.
Referenced by rtc14_read_registers(), rtc14_set_datetime_24h(), and temphum27_read_data().
iic0_clear_receive_state()
static void iic0_clear_receive_state (void) static
Clear receive flags before starting an IIC read phase.
Definition at line 106 of file iic0_bus.c.
References iic0_set_receive_nack(), IIC_ICMR3_WAIT, IIC_ICSR2_NACKF, and IIC_ICSR2_STOP.
Referenced by iic0_bus_init(), and iic0_bus_read_after_restart().
iic0_configure_bitrate()
static int iic0_configure_bitrate (uint32_t pclkb_hz, uint32_t bitrate_hz) static
Calculate and apply IIC0 clock timing registers.
Parameters
[in] pclkb_hz Peripheral clock B frequency in hertz.
[in] bitrate_hz Bitrate hz value.
Returns
Zero on success; otherwise a negative error code.
Definition at line 182 of file iic0_bus.c.
References IIC_ICFER_NFE, IIC_ICFER_SCLE, IIC_ICMR1_CKS_SHIFT, IIC_ICMR3_NF_MASK, RTC14_ERROR_CLOCK, and RTC14_OK.
Referenced by iic0_bus_init().
iic0_configure_pins()
static void iic0_configure_pins (void) static
Configure pins.
Definition at line 140 of file iic0_bus.c.
References PFS_NCODR_OPEN_DRAIN, PFS_PCR_PULLUP, PFS_PDR_OUTPUT, PFS_PMR_PERIPHERAL, PFS_PODR_HIGH, and PFS_PSEL.
Referenced by iic0_bus_init().
iic0_request_stop()
static int iic0_request_stop (void) static
Generate an IIC STOP condition and wait for bus release.
Returns
Result value.
Definition at line 118 of file iic0_bus.c.
References iic0_wait_set(), IIC_ICCR2_SP, IIC_ICSR2_NACKF, IIC_ICSR2_STOP, RTC14_ERROR_TIMEOUT, and RTC14_OK.
Referenced by iic0_bus_write().
iic0_set_receive_nack()
static void iic0_set_receive_nack (uint8_t nack) static
Configure the ACK/NACK response used for the next received byte.
Parameters
[in] nack Nonzero to send NACK after the next received byte.
Definition at line 86 of file iic0_bus.c.
References IIC_ICMR3_ACKBT, and IIC_ICMR3_ACKWP.
Referenced by iic0_bus_read_after_restart(), and iic0_clear_receive_state().
iic0_wait_clear()
static int iic0_wait_clear (volatile uint8_t * reg, uint8_t mask) static
Wait until all requested register bits become clear.
Parameters
[in] reg Register containing the bits to test.
[in] mask Bit mask to test or modify.
Returns
Result value.
Definition at line 39 of file iic0_bus.c.
References APP_I2C_TIMEOUT, RTC14_ERROR_TIMEOUT, and RTC14_OK.
Referenced by iic0_bus_read_after_restart(), and iic0_bus_write().
iic0_wait_set()
static int iic0_wait_set (volatile uint8_t * reg, uint8_t mask) static
Wait until all requested register bits become set.
Parameters
[in] reg Register containing the bits to test.
[in] mask Bit mask to test or modify.
Returns
Result value.
Definition at line 17 of file iic0_bus.c.
References APP_I2C_TIMEOUT, RTC14_ERROR_TIMEOUT, and RTC14_OK.
Referenced by iic0_bus_read_after_restart(), iic0_bus_write(), and iic0_request_stop().
iic0_wait_transmit_flag()
static int iic0_wait_transmit_flag (uint8_t mask) static
Wait for the next IIC transmit-ready or completion flag.
Parameters
[in] mask Bit mask to test or modify.
Returns
Result value.
Definition at line 60 of file iic0_bus.c.
References APP_I2C_TIMEOUT, IIC_ICSR2_NACKF, RTC14_ERROR_NACK, RTC14_ERROR_TIMEOUT, and RTC14_OK.
Referenced by iic0_bus_write().