R7FA4M2 Multi-Click Smartwatch: include/iic0_bus.h File Reference
iic0_bus.h File Reference
Shared polling IIC0 master interface.
#include <stdint.h>
Functions
int iic0_bus_init (void)
Initialize IIC0 on P400/P401 at the configured bus speed.
int iic0_bus_write (uint8_t address, const uint8_t *data, uint32_t length, uint8_t restart_after_write)
Write one transaction to a 7-bit I2C address.
int iic0_bus_read_after_restart (uint8_t address, uint8_t *data, uint32_t length)
Read bytes after a repeated START generated by the write phase.
Detailed Description
Shared polling IIC0 master interface.
Definition in file iic0_bus.h.
Function Documentation
iic0_bus_init()
int iic0_bus_init (void)
Initialize IIC0 on P400/P401 at the configured bus speed.
Returns
RTC14_OK on success; otherwise a negative application error code.
Initialize IIC0 on P400/P401 at the configured bus speed.
Returns
Zero on success; otherwise a negative error code.
Definition at line 256 of file iic0_bus.c.
References APP_I2C_BITRATE_HZ, iic0_clear_receive_state(), iic0_configure_bitrate(), iic0_configure_pins(), IIC_ICCR1_ICE, IIC_ICCR1_IICRST, system_clocks_t::pclkb, RTC14_OK, and SYSTEM_GetClocksFrequency().
Referenced by rtc14_init().
iic0_bus_read_after_restart()
int iic0_bus_read_after_restart (uint8_t address, uint8_t * data, uint32_t length)
Read bytes after a repeated START generated by the write phase.
Parameters
[in] address 7-bit target address.
[out] data Destination byte buffer.
[in] length Number of bytes to receive.
Returns
RTC14_OK on success; otherwise a negative application error code.
Parameters
[in] address 7-bit I2C device address.
[out] data Data buffer.
[in] length Number of bytes in the buffer.
Returns
Zero on success; otherwise a negative error code.
Definition at line 369 of file iic0_bus.c.
References iic0_clear_receive_state(), iic0_set_receive_nack(), iic0_wait_clear(), iic0_wait_set(), IIC_ICCR2_RS, IIC_ICCR2_SP, IIC_ICCR2_TRS, IIC_ICMR3_WAIT, IIC_ICSR2_NACKF, IIC_ICSR2_RDRF, IIC_ICSR2_STOP, RTC14_ERROR_ARGUMENT, RTC14_ERROR_NACK, and RTC14_OK.
Referenced by rtc14_read_registers(), and temphum27_read_data().
iic0_bus_write()
int iic0_bus_write (uint8_t address, const uint8_t * data, uint32_t length, uint8_t restart_after_write)
Write one transaction to a 7-bit I2C address.
Parameters
[in] address 7-bit target address.
[in] data Source byte buffer.
[in] length Number of bytes to transmit.
[in] restart_after_write Nonzero to generate a repeated START instead of STOP.
Returns
RTC14_OK on success; otherwise a negative application error code.
Write one transaction to a 7-bit I2C address.
Parameters
[in] address 7-bit I2C device address.
[in] data Data buffer.
[in] length Number of bytes in the buffer.
[in] restart_after_write Nonzero to leave the bus in repeated-START state.
Returns
Zero on success; otherwise a negative error code.
Definition at line 299 of file iic0_bus.c.
References iic0_request_stop(), iic0_wait_clear(), iic0_wait_set(), iic0_wait_transmit_flag(), IIC_ICCR2_BBSY, IIC_ICCR2_RS, IIC_ICCR2_ST, IIC_ICSR2_NACKF, IIC_ICSR2_STOP, IIC_ICSR2_TDRE, IIC_ICSR2_TEND, RTC14_ERROR_ARGUMENT, and RTC14_OK.
Referenced by rtc14_read_registers(), rtc14_set_datetime_24h(), and temphum27_read_data().