R7FA4M2 Multi-Click Smartwatch: src/ips2_display.c File Reference
ips2_display.c File Reference
IPS Display 2 initialization, graphics primitives and smartwatch UI.
#include "ips2_display.h"
#include "app_config.h"
#include "ra4m2_baremetal.h"
Macros
#define IPS2_CS_MASK (1U << 8)
#define IPS2_RST_MASK (1U << 10)
#define IPS2_DC_MASK (1U << 15)
#define IPS2_BCK_MASK (1U << 1)
#define IPS2_CMD_SLPOUT (0x11U)
#define IPS2_CMD_INVON (0x21U)
#define IPS2_CMD_DISPON (0x29U)
#define IPS2_CMD_CASET (0x2AU)
#define IPS2_CMD_RASET (0x2BU)
#define IPS2_CMD_RAMWR (0x2CU)
#define IPS2_CMD_MADCTL (0x36U)
#define IPS2_CMD_COLMOD (0x3AU)
#define IPS2_CMD_PORCTRL (0xB2U)
#define IPS2_CMD_GCTRL (0xB7U)
#define IPS2_CMD_VCOMS (0xBBU)
#define IPS2_CMD_VDVVRHEN (0xC2U)
#define IPS2_CMD_VRHS (0xC3U)
#define IPS2_CMD_VDVSET (0xC4U)
#define IPS2_CMD_FRCTR2 (0xC6U)
#define IPS2_CMD_PWCTRL1 (0xD0U)
#define IPS2_CMD_PVGAMCTRL (0xE0U)
#define IPS2_CMD_NVGAMCTRL (0xE1U)
#define IPS2_COLOR_BG (0x0842U)
#define IPS2_COLOR_CARD (0x10C4U)
#define IPS2_COLOR_CARD_2 (0x18E6U)
#define IPS2_COLOR_WHITE (0xFFFFU)
#define IPS2_COLOR_SOFT_WHITE (0xDEDBU)
#define IPS2_COLOR_MUTED (0x7BEFU)
#define IPS2_COLOR_CYAN (0x07FFU)
#define IPS2_COLOR_BLUE (0x249FU)
#define IPS2_COLOR_DARK_CYAN (0x0318U)
#define IPS2_COLOR_ERROR (0xF986U)
#define IPS2_COLOR_ORANGE (0xFD20U)
#define IPS2_COLOR_DEEP_ORANGE (0xA280U)
#define IPS2_COLOR_AQUA (0x4E7FU)
#define IPS2_COLOR_YELLOW (0xFFE0U)
#define IPS2_COLOR_SKY_DAY_TOP (0x147DU)
#define IPS2_COLOR_SKY_DAY_MID (0x24BFU)
#define IPS2_COLOR_SKY_DAY_LOW (0x65BFU)
#define IPS2_COLOR_SKY_NIGHT_TOP (0x0008U)
#define IPS2_COLOR_SKY_NIGHT_MID (0x0842U)
#define IPS2_COLOR_SKY_NIGHT_LOW (0x18A7U)
#define IPS2_COLOR_HORIZON_DAY (0xF5C9U)
#define IPS2_COLOR_HORIZON_NIGHT (0x2948U)
Functions
static volatile ra4m2_sci_registers_t * ips2_sci0 (void)
Return the SCI0 register view used by IPS Display 2 Click.
static void ips2_cs_low (void)
Assert the display chip-select signal.
static void ips2_cs_high (void)
Deassert the display chip-select signal.
static void ips2_rst_low (void)
Assert the display reset signal.
static void ips2_rst_high (void)
Deassert the display reset signal.
static void ips2_dc_low (void)
Select display command mode.
static void ips2_dc_high (void)
Select display data mode.
static void ips2_bck_low (void)
Disable the display backlight.
static void ips2_bck_high (void)
Enable the display backlight.
static void ips2_delay_ms (uint32_t milliseconds)
Handle delay ms.
static void ips2_configure_pins (void)
Configure pins.
static int ips2_sci0_set_speed (uint32_t pclka_hz, uint32_t speed_hz)
Handle sci0 set speed.
static int ips2_spi_init (uint32_t pclka_hz)
Handle spi init.
static void ips2_spi_write_byte (uint8_t value)
Transfer one byte over SCI0 simple SPI.
static void ips2_spi_wait_complete (void)
Wait until the SCI0 transmission is complete.
static void ips2_write_command (uint8_t command)
Send one command byte to the display controller.
static void ips2_write_command_data (uint8_t command, const uint8_t *data, uint32_t length)
Send a display command followed by its data payload.
static void ips2_set_window (uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1)
Select the rectangular display RAM write window.
static void ips2_fill_rect (uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t color)
Fill a clipped rectangular area with one RGB565 color.
static void ips2_draw_frame (uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t thickness, uint16_t color)
Draw a rectangular frame with the requested thickness.
static const uint8_t * ips2_glyph (char character)
Return the compact 5x7 bitmap for one supported character.
static uint16_t ips2_text_width (const char *text, uint8_t scale)
Calculate rendered text width for the selected font scale.
static void ips2_draw_char (uint16_t x, uint16_t y, char character, uint8_t scale, uint16_t color)
Draw one scaled 5x7 character.
static void ips2_draw_text (uint16_t x, uint16_t y, const char *text, uint8_t scale, uint16_t color)
Draw a null-terminated text string.
static void ips2_draw_text_centered (uint16_t y, const char *text, uint8_t scale, uint16_t color)
Draw text centered horizontally on the display.
static void ips2_draw_text_opaque (uint16_t x, uint16_t y, const char *text, uint8_t scale, uint16_t foreground, uint16_t background)
Draw text while repainting its rectangular background.
void ips2_invalidate_screen (void)
Invalidate screen.
static void ips2_draw_text_in_rect_centered (uint16_t x, uint16_t y, uint16_t width, const char *text, uint8_t scale, uint16_t color)
Draw text centered inside a rectangular region.
static uint32_t ips2_isqrt (uint32_t value)
Calculate the integer square root of an unsigned value.
static void ips2_draw_filled_circle (int32_t center_x, int32_t center_y, uint16_t radius, uint16_t color)
Draw a clipped filled circle.
static void ips2_draw_line (int32_t x0, int32_t y0, int32_t x1, int32_t y1, uint16_t thickness, uint16_t color)
Draw a line segment with configurable thickness.
static void ips2_format_tenths (char *text, int32_t value, char unit)
Format a signed fixed-point tenths value as text.
static void ips2_format_two_digits (char *text, uint32_t value)
Format a value as two decimal digits.
static void ips2_format_three_digits (char *text, uint32_t value)
Format a value as three decimal digits.
static void ips2_draw_bluetooth_symbol (uint16_t x, uint16_t y, uint16_t color)
Draw the compact Bluetooth status symbol.
void ips2_render_ble_status (uint8_t connected, app_screen_t screen)
Render ble status.
static void ips2_draw_dashboard_thermometer_icon (uint16_t x, uint16_t y)
Draw the compact dashboard temperature icon.
static void ips2_draw_dashboard_humidity_icon (uint16_t x, uint16_t y)
Draw the compact dashboard humidity icon.
static void ips2_draw_dashboard_static (void)
Draw all static elements of the smartwatch dashboard.
static void ips2_format_dashboard_date (char *date, const rtc14_datetime_t *datetime)
Format the RTC date for the smartwatch dashboard.
static void ips2_draw_dashboard_date (const rtc14_datetime_t *datetime)
Draw the weekday and date area of the dashboard.
static void ips2_draw_dashboard_time (const rtc14_datetime_t *datetime)
Draw the dashboard clock and AM/PM indicator.
static void ips2_draw_dashboard_environment (const temphum27_data_t *environment)
Draw compact temperature and humidity summary cards.
void ips2_render_dashboard (const rtc14_datetime_t *datetime, const temphum27_data_t *environment, uint8_t ble_connected)
Render dashboard.
static uint16_t ips2_temperature_color (int16_t temperature_tenths)
Map a temperature value to an RGB565 cold-to-hot color.
static int16_t ips2_approach_i16 (int16_t current, int16_t target, int16_t step)
Move a signed animated value toward its target by a bounded step.
static uint16_t ips2_approach_u16 (uint16_t current, uint16_t target, uint16_t step)
Move an unsigned animated value toward its target by a bounded step.
static void ips2_draw_environment_static (void)
Draw all static elements of the environment screen.
static void ips2_draw_temperature_dynamic (int16_t temperature_tenths, uint8_t valid)
Draw the animated thermometer and temperature value.
static void ips2_draw_humidity_drop (uint16_t humidity_tenths, uint8_t valid, uint32_t animation_ms)
Draw the humidity droplet and its animated water level.
void ips2_render_environment (const temphum27_data_t *environment, uint8_t ble_connected, uint32_t animation_ms)
Render environment.
static uint8_t ips2_datetime_hour24 (const rtc14_datetime_t *datetime)
Convert the decoded RTC hour to a 24-hour value.
static uint16_t ips2_scene_color_at_y (uint8_t daylight, uint16_t y)
Return the sky gradient color for a vertical scene coordinate.
static void ips2_fill_scene_rect (uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint8_t daylight)
Restore a rectangular area using the current sky gradient.
static uint16_t ips2_astronomy_arc_y (uint16_t phase_minutes)
Calculate the lowered celestial trajectory height for a phase.
static void ips2_draw_astronomy_arc (uint8_t daylight)
Draw guide points along the sun/moon trajectory.
static void ips2_draw_night_stars (void)
Draw the static nighttime star field.
static void ips2_draw_horizon_silhouette (uint8_t daylight)
Draw the day or night horizon silhouette.
static void ips2_draw_astronomy_static (uint8_t daylight)
Draw all static elements of the Time of Day screen.
static void ips2_clear_celestial_region (uint16_t body_x, uint16_t body_y, uint8_t daylight)
Restore the sky behind a previous celestial-body position.
static void ips2_draw_celestial_body (uint16_t body_x, uint16_t body_y, uint8_t daylight)
Draw the transparent-background sun or crescent moon.
void ips2_render_astronomy (const rtc14_datetime_t *datetime, uint8_t ble_connected, uint32_t animation_ms)
Render astronomy.
static void ips2_draw_timer_static (void)
Draw all static elements of the stopwatch screen.
static void ips2_draw_timer_actions (uint32_t elapsed_ms, uint8_t running)
Draw context-sensitive B3 and B4 stopwatch action hints.
static void ips2_draw_timer_state (uint32_t elapsed_ms, uint8_t running)
Draw the current stopwatch state label.
void ips2_render_timer (uint32_t elapsed_ms, uint8_t running, uint8_t ble_connected)
Render timer.
void ips2_render_error (uint8_t ble_connected)
Render error.
int ips2_init (uint32_t pclka_hz)
Initialize the module.
Variables
static uint8_t ips2_frame_drawn
static uint8_t ips2_last_day = 0xFFU
static uint8_t ips2_last_month = 0xFFU
static uint8_t ips2_last_year = 0xFFU
static uint8_t ips2_last_weekday = 0xFFU
static uint8_t ips2_last_hour = 0xFFU
static uint8_t ips2_last_minute = 0xFFU
static uint8_t ips2_last_second = 0xFFU
static uint8_t ips2_last_mode = 0xFFU
static uint8_t ips2_last_astronomy_mode = 0xFFU
static uint8_t ips2_last_timer_hour = 0xFFU
static uint8_t ips2_last_timer_minute = 0xFFU
static uint8_t ips2_last_timer_second = 0xFFU
static uint8_t ips2_last_timer_state = 0xFFU
static uint8_t ips2_last_timer_b3_action = 0xFFU
static uint8_t ips2_last_timer_b4_action = 0xFFU
static int16_t ips2_last_temperature_tenths = (int16_t)0x7FFF
static uint16_t ips2_last_humidity_tenths = 0xFFFFU
static uint8_t ips2_last_environment_valid = 0xFFU
static uint8_t ips2_last_ble_connected = 0xFFU
static int16_t ips2_animated_temperature_tenths = (int16_t)0x7FFF
static uint16_t ips2_animated_humidity_tenths = 0xFFFFU
static int16_t ips2_last_drawn_temperature_tenths = (int16_t)0x7FFF
static uint16_t ips2_last_drawn_humidity_tenths = 0xFFFFU
static uint16_t ips2_last_body_x = 0xFFFFU
static uint16_t ips2_last_body_y = 0xFFFFU
Detailed Description
IPS Display 2 initialization, graphics primitives and smartwatch UI.
Definition in file ips2_display.c.
Macro Definition Documentation
IPS2_BCK_MASK
#define IPS2_BCK_MASK (1U << 1)
Definition at line 14 of file ips2_display.c.
IPS2_CMD_CASET
#define IPS2_CMD_CASET (0x2AU)
Definition at line 18 of file ips2_display.c.
IPS2_CMD_COLMOD
#define IPS2_CMD_COLMOD (0x3AU)
Definition at line 22 of file ips2_display.c.
IPS2_CMD_DISPON
#define IPS2_CMD_DISPON (0x29U)
Definition at line 17 of file ips2_display.c.
IPS2_CMD_FRCTR2
#define IPS2_CMD_FRCTR2 (0xC6U)
Definition at line 29 of file ips2_display.c.
IPS2_CMD_GCTRL
#define IPS2_CMD_GCTRL (0xB7U)
Definition at line 24 of file ips2_display.c.
IPS2_CMD_INVON
#define IPS2_CMD_INVON (0x21U)
Definition at line 16 of file ips2_display.c.
IPS2_CMD_MADCTL
#define IPS2_CMD_MADCTL (0x36U)
Definition at line 21 of file ips2_display.c.
IPS2_CMD_NVGAMCTRL
#define IPS2_CMD_NVGAMCTRL (0xE1U)
Definition at line 32 of file ips2_display.c.
IPS2_CMD_PORCTRL
#define IPS2_CMD_PORCTRL (0xB2U)
Definition at line 23 of file ips2_display.c.
IPS2_CMD_PVGAMCTRL
#define IPS2_CMD_PVGAMCTRL (0xE0U)
Definition at line 31 of file ips2_display.c.
IPS2_CMD_PWCTRL1
#define IPS2_CMD_PWCTRL1 (0xD0U)
Definition at line 30 of file ips2_display.c.
IPS2_CMD_RAMWR
#define IPS2_CMD_RAMWR (0x2CU)
Definition at line 20 of file ips2_display.c.
IPS2_CMD_RASET
#define IPS2_CMD_RASET (0x2BU)
Definition at line 19 of file ips2_display.c.
IPS2_CMD_SLPOUT
#define IPS2_CMD_SLPOUT (0x11U)
Definition at line 15 of file ips2_display.c.
IPS2_CMD_VCOMS
#define IPS2_CMD_VCOMS (0xBBU)
Definition at line 25 of file ips2_display.c.
IPS2_CMD_VDVSET
#define IPS2_CMD_VDVSET (0xC4U)
Definition at line 28 of file ips2_display.c.
IPS2_CMD_VDVVRHEN
#define IPS2_CMD_VDVVRHEN (0xC2U)
Definition at line 26 of file ips2_display.c.
IPS2_CMD_VRHS
#define IPS2_CMD_VRHS (0xC3U)
Definition at line 27 of file ips2_display.c.
IPS2_COLOR_AQUA
#define IPS2_COLOR_AQUA (0x4E7FU)
Definition at line 45 of file ips2_display.c.
IPS2_COLOR_BG
#define IPS2_COLOR_BG (0x0842U)
Definition at line 33 of file ips2_display.c.
IPS2_COLOR_BLUE
#define IPS2_COLOR_BLUE (0x249FU)
Definition at line 40 of file ips2_display.c.
IPS2_COLOR_CARD
#define IPS2_COLOR_CARD (0x10C4U)
Definition at line 34 of file ips2_display.c.
IPS2_COLOR_CARD_2
#define IPS2_COLOR_CARD_2 (0x18E6U)
Definition at line 35 of file ips2_display.c.
IPS2_COLOR_CYAN
#define IPS2_COLOR_CYAN (0x07FFU)
Definition at line 39 of file ips2_display.c.
IPS2_COLOR_DARK_CYAN
#define IPS2_COLOR_DARK_CYAN (0x0318U)
Definition at line 41 of file ips2_display.c.
IPS2_COLOR_DEEP_ORANGE
#define IPS2_COLOR_DEEP_ORANGE (0xA280U)
Definition at line 44 of file ips2_display.c.
IPS2_COLOR_ERROR
#define IPS2_COLOR_ERROR (0xF986U)
Definition at line 42 of file ips2_display.c.
IPS2_COLOR_HORIZON_DAY
#define IPS2_COLOR_HORIZON_DAY (0xF5C9U)
Definition at line 53 of file ips2_display.c.
IPS2_COLOR_HORIZON_NIGHT
#define IPS2_COLOR_HORIZON_NIGHT (0x2948U)
Definition at line 54 of file ips2_display.c.
IPS2_COLOR_MUTED
#define IPS2_COLOR_MUTED (0x7BEFU)
Definition at line 38 of file ips2_display.c.
IPS2_COLOR_ORANGE
#define IPS2_COLOR_ORANGE (0xFD20U)
Definition at line 43 of file ips2_display.c.
IPS2_COLOR_SKY_DAY_LOW
#define IPS2_COLOR_SKY_DAY_LOW (0x65BFU)
Definition at line 49 of file ips2_display.c.
IPS2_COLOR_SKY_DAY_MID
#define IPS2_COLOR_SKY_DAY_MID (0x24BFU)
Definition at line 48 of file ips2_display.c.
IPS2_COLOR_SKY_DAY_TOP
#define IPS2_COLOR_SKY_DAY_TOP (0x147DU)
Definition at line 47 of file ips2_display.c.
IPS2_COLOR_SKY_NIGHT_LOW
#define IPS2_COLOR_SKY_NIGHT_LOW (0x18A7U)
Definition at line 52 of file ips2_display.c.
IPS2_COLOR_SKY_NIGHT_MID
#define IPS2_COLOR_SKY_NIGHT_MID (0x0842U)
Definition at line 51 of file ips2_display.c.
IPS2_COLOR_SKY_NIGHT_TOP
#define IPS2_COLOR_SKY_NIGHT_TOP (0x0008U)
Definition at line 50 of file ips2_display.c.
IPS2_COLOR_SOFT_WHITE
#define IPS2_COLOR_SOFT_WHITE (0xDEDBU)
Definition at line 37 of file ips2_display.c.
IPS2_COLOR_WHITE
#define IPS2_COLOR_WHITE (0xFFFFU)
Definition at line 36 of file ips2_display.c.
IPS2_COLOR_YELLOW
#define IPS2_COLOR_YELLOW (0xFFE0U)
Definition at line 46 of file ips2_display.c.
IPS2_CS_MASK
#define IPS2_CS_MASK (1U << 8)
Definition at line 11 of file ips2_display.c.
IPS2_DC_MASK
#define IPS2_DC_MASK (1U << 15)
Definition at line 13 of file ips2_display.c.
IPS2_RST_MASK
#define IPS2_RST_MASK (1U << 10)
Definition at line 12 of file ips2_display.c.
Function Documentation
ips2_approach_i16()
static int16_t ips2_approach_i16 (int16_t current, int16_t target, int16_t step) static
Move a signed animated value toward its target by a bounded step.
Parameters
[in] current Current animation value.
[in] target Target animation value.
[in] step Maximum change applied in one update.
Returns
Calculated or converted value.
Definition at line 1355 of file ips2_display.c.
Referenced by ips2_render_environment().
ips2_approach_u16()
static uint16_t ips2_approach_u16 (uint16_t current, uint16_t target, uint16_t step) static
Move an unsigned animated value toward its target by a bounded step.
Parameters
[in] current Current animation value.
[in] target Target animation value.
[in] step Maximum change applied in one update.
Returns
Calculated or converted value.
Definition at line 1379 of file ips2_display.c.
Referenced by ips2_render_environment().
ips2_astronomy_arc_y()
static uint16_t ips2_astronomy_arc_y (uint16_t phase_minutes) static
Calculate the lowered celestial trajectory height for a phase.
Parameters
[in] phase_minutes Minutes elapsed in the current 12-hour celestial phase.
Returns
Calculated or converted value.
Definition at line 1792 of file ips2_display.c.
Referenced by ips2_draw_astronomy_arc(), and ips2_render_astronomy().
ips2_bck_high()
static void ips2_bck_high (void) static
Enable the display backlight.
Definition at line 138 of file ips2_display.c.
References IPS2_BCK_MASK.
Referenced by ips2_init().
ips2_bck_low()
static void ips2_bck_low (void) static
Disable the display backlight.
Definition at line 132 of file ips2_display.c.
References IPS2_BCK_MASK.
Referenced by ips2_init().
ips2_clear_celestial_region()
static void ips2_clear_celestial_region (uint16_t body_x, uint16_t body_y, uint8_t daylight) static
Restore the sky behind a previous celestial-body position.
Parameters
[in] body_x Celestial-body center x-coordinate.
[in] body_y Celestial-body center y-coordinate.
[in] daylight Nonzero for the daytime scene.
Definition at line 1887 of file ips2_display.c.
References ips2_fill_scene_rect(), and IPS2_WIDTH.
Referenced by ips2_render_astronomy().
ips2_configure_pins()
static void ips2_configure_pins (void) static
Configure pins.
Definition at line 157 of file ips2_display.c.
References PFS_PDR_OUTPUT, PFS_PMR_PERIPHERAL, PFS_PODR_HIGH, and PFS_PSEL.
Referenced by ips2_init().
ips2_cs_high()
static void ips2_cs_high (void) static
Deassert the display chip-select signal.
Definition at line 102 of file ips2_display.c.
References IPS2_CS_MASK.
Referenced by ips2_draw_humidity_drop(), ips2_draw_text_opaque(), ips2_fill_rect(), ips2_init(), ips2_write_command(), and ips2_write_command_data().
ips2_cs_low()
static void ips2_cs_low (void) static
Assert the display chip-select signal.
Definition at line 96 of file ips2_display.c.
References IPS2_CS_MASK.
Referenced by ips2_draw_humidity_drop(), ips2_draw_text_opaque(), ips2_fill_rect(), ips2_write_command(), and ips2_write_command_data().
ips2_datetime_hour24()
static uint8_t ips2_datetime_hour24 (const rtc14_datetime_t * datetime) static
Convert the decoded RTC hour to a 24-hour value.
Parameters
[in] datetime Decoded RTC date and time.
Returns
Calculated or converted value.
Definition at line 1697 of file ips2_display.c.
References rtc14_datetime_t::hour, rtc14_datetime_t::is_24_hour, and rtc14_datetime_t::is_pm.
Referenced by ips2_render_astronomy().
ips2_dc_high()
static void ips2_dc_high (void) static
Select display data mode.
Definition at line 126 of file ips2_display.c.
References IPS2_DC_MASK.
Referenced by ips2_draw_humidity_drop(), ips2_draw_text_opaque(), ips2_fill_rect(), ips2_init(), and ips2_write_command_data().
ips2_dc_low()
static void ips2_dc_low (void) static
Select display command mode.
Definition at line 120 of file ips2_display.c.
References IPS2_DC_MASK.
Referenced by ips2_write_command(), and ips2_write_command_data().
ips2_delay_ms()
static void ips2_delay_ms (uint32_t milliseconds) static
Handle delay ms.
Parameters
[in] milliseconds Delay duration in milliseconds.
Definition at line 145 of file ips2_display.c.
Referenced by ips2_init().
ips2_draw_astronomy_arc()
static void ips2_draw_astronomy_arc (uint8_t daylight) static
Draw guide points along the sun/moon trajectory.
Parameters
[in] daylight Nonzero for the daytime scene.
Definition at line 1805 of file ips2_display.c.
References ips2_astronomy_arc_y(), IPS2_COLOR_MUTED, IPS2_COLOR_SOFT_WHITE, and ips2_fill_rect().
Referenced by ips2_draw_astronomy_static(), and ips2_render_astronomy().
ips2_draw_astronomy_static()
static void ips2_draw_astronomy_static (uint8_t daylight) static
Draw all static elements of the Time of Day screen.
Parameters
[in] daylight Nonzero for the daytime scene.
Definition at line 1857 of file ips2_display.c.
References IPS2_COLOR_BG, IPS2_COLOR_CARD, IPS2_COLOR_CARD_2, IPS2_COLOR_CYAN, IPS2_COLOR_MUTED, IPS2_COLOR_ORANGE, IPS2_COLOR_SOFT_WHITE, ips2_draw_astronomy_arc(), ips2_draw_frame(), ips2_draw_horizon_silhouette(), ips2_draw_night_stars(), ips2_draw_text_centered(), ips2_fill_rect(), ips2_fill_scene_rect(), and IPS2_WIDTH.
Referenced by ips2_render_astronomy().
ips2_draw_bluetooth_symbol()
static void ips2_draw_bluetooth_symbol (uint16_t x, uint16_t y, uint16_t color) static
Draw the compact Bluetooth status symbol.
Parameters
[in] x Horizontal display coordinate.
[in] y Vertical display coordinate.
[in] color RGB565 drawing color.
Definition at line 951 of file ips2_display.c.
References ips2_fill_rect().
Referenced by ips2_render_ble_status().
ips2_draw_celestial_body()
static void ips2_draw_celestial_body (uint16_t body_x, uint16_t body_y, uint8_t daylight) static
Draw the transparent-background sun or crescent moon.
Parameters
[in] body_x Celestial-body center x-coordinate.
[in] body_y Celestial-body center y-coordinate.
[in] daylight Nonzero for the daytime scene.
Definition at line 1914 of file ips2_display.c.
References IPS2_COLOR_SOFT_WHITE, IPS2_COLOR_WHITE, IPS2_COLOR_YELLOW, ips2_draw_filled_circle(), ips2_draw_line(), and ips2_scene_color_at_y().
Referenced by ips2_render_astronomy().
ips2_draw_char()
static void ips2_draw_char (uint16_t x, uint16_t y, char character, uint8_t scale, uint16_t color) static
Draw one scaled 5x7 character.
Parameters
[in] x Horizontal display coordinate.
[in] y Vertical display coordinate.
[in] character Character to draw or look up.
[in] scale Integer font scale.
[in] color RGB565 drawing color.
Definition at line 569 of file ips2_display.c.
References ips2_fill_rect(), and ips2_glyph().
Referenced by ips2_draw_text().
ips2_draw_dashboard_date()
static void ips2_draw_dashboard_date (const rtc14_datetime_t * datetime) static
Draw the weekday and date area of the dashboard.
Parameters
[in] datetime Decoded RTC date and time.
Definition at line 1143 of file ips2_display.c.
References IPS2_COLOR_CARD, IPS2_COLOR_CYAN, IPS2_COLOR_SOFT_WHITE, ips2_draw_text_centered(), ips2_fill_rect(), ips2_format_dashboard_date(), and rtc14_datetime_t::weekday.
Referenced by ips2_render_dashboard().
ips2_draw_dashboard_environment()
static void ips2_draw_dashboard_environment (const temphum27_data_t * environment) static
Draw compact temperature and humidity summary cards.
Parameters
[in] environment Temperature and humidity measurement.
Definition at line 1218 of file ips2_display.c.
References temphum27_data_t::humidity_tenths_percent, IPS2_COLOR_CARD, IPS2_COLOR_SOFT_WHITE, ips2_draw_text_in_rect_centered(), ips2_fill_rect(), ips2_format_tenths(), ips2_last_environment_valid, ips2_last_humidity_tenths, ips2_last_temperature_tenths, temphum27_data_t::temperature_tenths_c, and temphum27_data_t::valid.
Referenced by ips2_render_dashboard().
ips2_draw_dashboard_humidity_icon()
static void ips2_draw_dashboard_humidity_icon (uint16_t x, uint16_t y) static
Draw the compact dashboard humidity icon.
Parameters
[in] x Horizontal display coordinate.
[in] y Vertical display coordinate.
Definition at line 1070 of file ips2_display.c.
References IPS2_COLOR_AQUA, IPS2_COLOR_CYAN, IPS2_COLOR_WHITE, and ips2_fill_rect().
Referenced by ips2_draw_dashboard_static().
ips2_draw_dashboard_static()
static void ips2_draw_dashboard_static (void) static
Draw all static elements of the smartwatch dashboard.
Definition at line 1091 of file ips2_display.c.
References IPS2_COLOR_BG, IPS2_COLOR_BLUE, IPS2_COLOR_CARD, IPS2_COLOR_CARD_2, IPS2_COLOR_CYAN, IPS2_COLOR_DARK_CYAN, IPS2_COLOR_DEEP_ORANGE, IPS2_COLOR_MUTED, ips2_draw_dashboard_humidity_icon(), ips2_draw_dashboard_thermometer_icon(), ips2_draw_frame(), ips2_draw_text(), ips2_draw_text_centered(), ips2_fill_rect(), IPS2_HEIGHT, and IPS2_WIDTH.
Referenced by ips2_render_dashboard().
ips2_draw_dashboard_thermometer_icon()
static void ips2_draw_dashboard_thermometer_icon (uint16_t x, uint16_t y) static
Draw the compact dashboard temperature icon.
Parameters
[in] x Horizontal display coordinate.
[in] y Vertical display coordinate.
Definition at line 1051 of file ips2_display.c.
References IPS2_COLOR_CARD, IPS2_COLOR_ERROR, IPS2_COLOR_ORANGE, and ips2_fill_rect().
Referenced by ips2_draw_dashboard_static().
ips2_draw_dashboard_time()
static void ips2_draw_dashboard_time (const rtc14_datetime_t * datetime) static
Draw the dashboard clock and AM/PM indicator.
Parameters
[in] datetime Decoded RTC date and time.
Definition at line 1169 of file ips2_display.c.
References rtc14_datetime_t::hour, IPS2_COLOR_BLUE, IPS2_COLOR_CARD, IPS2_COLOR_WHITE, ips2_draw_text(), ips2_draw_text_in_rect_centered(), ips2_fill_rect(), ips2_last_hour, ips2_last_minute, ips2_last_mode, ips2_text_width(), rtc14_datetime_t::is_24_hour, rtc14_datetime_t::is_pm, and rtc14_datetime_t::minute.
Referenced by ips2_render_dashboard().
ips2_draw_environment_static()
static void ips2_draw_environment_static (void) static
Draw all static elements of the environment screen.
Definition at line 1399 of file ips2_display.c.
References IPS2_COLOR_BG, IPS2_COLOR_CARD, IPS2_COLOR_CARD_2, IPS2_COLOR_CYAN, IPS2_COLOR_MUTED, IPS2_COLOR_SOFT_WHITE, ips2_draw_filled_circle(), ips2_draw_frame(), ips2_draw_text(), ips2_draw_text_centered(), ips2_draw_text_in_rect_centered(), ips2_fill_rect(), IPS2_HEIGHT, and IPS2_WIDTH.
Referenced by ips2_render_environment().
ips2_draw_filled_circle()
static void ips2_draw_filled_circle (int32_t center_x, int32_t center_y, uint16_t radius, uint16_t color) static
Draw a clipped filled circle.
Parameters
[in] center_x Center x value.
[in] center_y Center y value.
[in] radius Circle radius in pixels.
[in] color RGB565 drawing color.
Definition at line 797 of file ips2_display.c.
References ips2_fill_rect(), IPS2_HEIGHT, ips2_isqrt(), and IPS2_WIDTH.
Referenced by ips2_draw_celestial_body(), ips2_draw_environment_static(), and ips2_draw_temperature_dynamic().
ips2_draw_frame()
static void ips2_draw_frame (uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t thickness, uint16_t color) static
Draw a rectangular frame with the requested thickness.
Parameters
[in] x Horizontal display coordinate.
[in] y Vertical display coordinate.
[in] width Rectangle width in pixels.
[in] height Rectangle height in pixels.
[in] thickness Drawing thickness in pixels.
[in] color RGB565 drawing color.
Definition at line 448 of file ips2_display.c.
References ips2_fill_rect().
Referenced by ips2_draw_astronomy_static(), ips2_draw_dashboard_static(), ips2_draw_environment_static(), ips2_draw_timer_static(), and ips2_render_error().
ips2_draw_horizon_silhouette()
static void ips2_draw_horizon_silhouette (uint8_t daylight) static
Draw the day or night horizon silhouette.
Parameters
[in] daylight Nonzero for the daytime scene.
Definition at line 1843 of file ips2_display.c.
References IPS2_COLOR_CARD_2, IPS2_COLOR_DEEP_ORANGE, and ips2_fill_rect().
Referenced by ips2_draw_astronomy_static(), and ips2_render_astronomy().
ips2_draw_humidity_drop()
static void ips2_draw_humidity_drop (uint16_t humidity_tenths, uint8_t valid, uint32_t animation_ms) static
Draw the humidity droplet and its animated water level.
Parameters
[in] humidity_tenths Humidity tenths value.
[in] valid Valid value.
[in] animation_ms Animation timebase in milliseconds.
Definition at line 1496 of file ips2_display.c.
References IPS2_COLOR_AQUA, IPS2_COLOR_CARD, IPS2_COLOR_CYAN, IPS2_COLOR_WHITE, ips2_cs_high(), ips2_cs_low(), ips2_dc_high(), ips2_draw_text_in_rect_centered(), ips2_fill_rect(), ips2_format_tenths(), ips2_isqrt(), ips2_set_window(), ips2_spi_wait_complete(), and ips2_spi_write_byte().
Referenced by ips2_render_environment().
ips2_draw_line()
static void ips2_draw_line (int32_t x0, int32_t y0, int32_t x1, int32_t y1, uint16_t thickness, uint16_t color) static
Draw a line segment with configurable thickness.
Parameters
[in] x0 Left display coordinate.
[in] y0 Top display coordinate.
[in] x1 Right display coordinate.
[in] y1 Bottom display coordinate.
[in] thickness Drawing thickness in pixels.
[in] color RGB565 drawing color.
Definition at line 834 of file ips2_display.c.
References ips2_fill_rect(), IPS2_HEIGHT, and IPS2_WIDTH.
Referenced by ips2_draw_celestial_body().
ips2_draw_night_stars()
static void ips2_draw_night_stars (void) static
Draw the static nighttime star field.
Definition at line 1823 of file ips2_display.c.
References IPS2_COLOR_SOFT_WHITE, and ips2_fill_rect().
Referenced by ips2_draw_astronomy_static(), and ips2_render_astronomy().
ips2_draw_temperature_dynamic()
static void ips2_draw_temperature_dynamic (int16_t temperature_tenths, uint8_t valid) static
Draw the animated thermometer and temperature value.
Parameters
[in] temperature_tenths Temperature tenths value.
[in] valid Valid value.
Definition at line 1438 of file ips2_display.c.
References IPS2_COLOR_CARD, IPS2_COLOR_WHITE, ips2_draw_filled_circle(), ips2_draw_text_in_rect_centered(), ips2_fill_rect(), ips2_format_tenths(), and ips2_temperature_color().
Referenced by ips2_render_environment().
ips2_draw_text()
static void ips2_draw_text (uint16_t x, uint16_t y, const char * text, uint8_t scale, uint16_t color) static
Draw a null-terminated text string.
Parameters
[in] x Horizontal display coordinate.
[in] y Vertical display coordinate.
[in] text Null-terminated text string.
[in] scale Integer font scale.
[in] color RGB565 drawing color.
Definition at line 600 of file ips2_display.c.
References ips2_draw_char().
Referenced by ips2_draw_dashboard_static(), ips2_draw_dashboard_time(), ips2_draw_environment_static(), ips2_draw_text_centered(), ips2_draw_text_in_rect_centered(), and ips2_draw_timer_static().
ips2_draw_text_centered()
static void ips2_draw_text_centered (uint16_t y, const char * text, uint8_t scale, uint16_t color) static
Draw text centered horizontally on the display.
Parameters
[in] y Vertical display coordinate.
[in] text Null-terminated text string.
[in] scale Integer font scale.
[in] color RGB565 drawing color.
Definition at line 620 of file ips2_display.c.
References ips2_draw_text(), ips2_text_width(), and IPS2_WIDTH.
Referenced by ips2_draw_astronomy_static(), ips2_draw_dashboard_date(), ips2_draw_dashboard_static(), ips2_draw_environment_static(), ips2_draw_timer_actions(), ips2_draw_timer_state(), ips2_draw_timer_static(), and ips2_render_error().
ips2_draw_text_in_rect_centered()
static void ips2_draw_text_in_rect_centered (uint16_t x, uint16_t y, uint16_t width, const char * text, uint8_t scale, uint16_t color) static
Draw text centered inside a rectangular region.
Parameters
[in] x Horizontal display coordinate.
[in] y Vertical display coordinate.
[in] width Rectangle width in pixels.
[in] text Null-terminated text string.
[in] scale Integer font scale.
[in] color RGB565 drawing color.
Definition at line 739 of file ips2_display.c.
References ips2_draw_text(), and ips2_text_width().
Referenced by ips2_draw_dashboard_environment(), ips2_draw_dashboard_time(), ips2_draw_environment_static(), ips2_draw_humidity_drop(), and ips2_draw_temperature_dynamic().
ips2_draw_text_opaque()
static void ips2_draw_text_opaque (uint16_t x, uint16_t y, const char * text, uint8_t scale, uint16_t foreground, uint16_t background) static
Draw text while repainting its rectangular background.
Parameters
[in] x Horizontal display coordinate.
[in] y Vertical display coordinate.
[in] text Null-terminated text string.
[in] scale Integer font scale.
[in] foreground RGB565 text color.
[in] background RGB565 background color.
Definition at line 641 of file ips2_display.c.
References ips2_cs_high(), ips2_cs_low(), ips2_dc_high(), ips2_glyph(), ips2_set_window(), ips2_spi_wait_complete(), and ips2_spi_write_byte().
Referenced by ips2_render_astronomy(), and ips2_render_timer().
ips2_draw_timer_actions()
static void ips2_draw_timer_actions (uint32_t elapsed_ms, uint8_t running) static
Draw context-sensitive B3 and B4 stopwatch action hints.
Parameters
[in] elapsed_ms Stopwatch elapsed time in milliseconds.
[in] running Nonzero when the stopwatch is running.
Definition at line 2095 of file ips2_display.c.
References IPS2_COLOR_BG, IPS2_COLOR_CYAN, IPS2_COLOR_ERROR, IPS2_COLOR_MUTED, ips2_draw_text_centered(), ips2_fill_rect(), ips2_last_timer_b3_action, ips2_last_timer_b4_action, and IPS2_WIDTH.
Referenced by ips2_render_timer().
ips2_draw_timer_state()
static void ips2_draw_timer_state (uint32_t elapsed_ms, uint8_t running) static
Draw the current stopwatch state label.
Parameters
[in] elapsed_ms Stopwatch elapsed time in milliseconds.
[in] running Nonzero when the stopwatch is running.
Definition at line 2154 of file ips2_display.c.
References IPS2_COLOR_BG, IPS2_COLOR_CYAN, IPS2_COLOR_ERROR, IPS2_COLOR_SOFT_WHITE, ips2_draw_text_centered(), ips2_fill_rect(), ips2_last_timer_state, and IPS2_WIDTH.
Referenced by ips2_render_timer().
ips2_draw_timer_static()
static void ips2_draw_timer_static (void) static
Draw all static elements of the stopwatch screen.
Definition at line 2072 of file ips2_display.c.
References IPS2_COLOR_BG, IPS2_COLOR_CARD, IPS2_COLOR_CARD_2, IPS2_COLOR_CYAN, IPS2_COLOR_DARK_CYAN, IPS2_COLOR_MUTED, IPS2_COLOR_SOFT_WHITE, ips2_draw_frame(), ips2_draw_text(), ips2_draw_text_centered(), ips2_fill_rect(), IPS2_HEIGHT, and IPS2_WIDTH.
Referenced by ips2_render_timer().
ips2_fill_rect()
static void ips2_fill_rect (uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t color) static
Fill a clipped rectangular area with one RGB565 color.
Parameters
[in] x Horizontal display coordinate.
[in] y Vertical display coordinate.
[in] width Rectangle width in pixels.
[in] height Rectangle height in pixels.
[in] color RGB565 drawing color.
Definition at line 396 of file ips2_display.c.
References ips2_cs_high(), ips2_cs_low(), ips2_dc_high(), IPS2_HEIGHT, ips2_set_window(), ips2_spi_wait_complete(), ips2_spi_write_byte(), and IPS2_WIDTH.
Referenced by ips2_draw_astronomy_arc(), ips2_draw_astronomy_static(), ips2_draw_bluetooth_symbol(), ips2_draw_char(), ips2_draw_dashboard_date(), ips2_draw_dashboard_environment(), ips2_draw_dashboard_humidity_icon(), ips2_draw_dashboard_static(), ips2_draw_dashboard_thermometer_icon(), ips2_draw_dashboard_time(), ips2_draw_environment_static(), ips2_draw_filled_circle(), ips2_draw_frame(), ips2_draw_horizon_silhouette(), ips2_draw_humidity_drop(), ips2_draw_line(), ips2_draw_night_stars(), ips2_draw_temperature_dynamic(), ips2_draw_timer_actions(), ips2_draw_timer_state(), ips2_draw_timer_static(), ips2_fill_scene_rect(), ips2_init(), ips2_render_ble_status(), ips2_render_error(), and ips2_render_timer().
ips2_fill_scene_rect()
static void ips2_fill_scene_rect (uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint8_t daylight) static
Restore a rectangular area using the current sky gradient.
Parameters
[in] x Horizontal display coordinate.
[in] y Vertical display coordinate.
[in] width Rectangle width in pixels.
[in] height Rectangle height in pixels.
[in] daylight Nonzero for the daytime scene.
Definition at line 1751 of file ips2_display.c.
References ips2_fill_rect(), IPS2_HEIGHT, ips2_scene_color_at_y(), and IPS2_WIDTH.
Referenced by ips2_clear_celestial_region(), and ips2_draw_astronomy_static().
ips2_format_dashboard_date()
static void ips2_format_dashboard_date (char * date, const rtc14_datetime_t * datetime) static
Format the RTC date for the smartwatch dashboard.
Parameters
[in] date Date value.
[in] datetime Decoded RTC date and time.
Definition at line 1122 of file ips2_display.c.
References rtc14_datetime_t::day, rtc14_datetime_t::month, and rtc14_datetime_t::year.
Referenced by ips2_draw_dashboard_date().
ips2_format_tenths()
static void ips2_format_tenths (char * text, int32_t value, char unit) static
Format a signed fixed-point tenths value as text.
Parameters
[in] text Null-terminated text string.
[in] value Value to process.
[in] unit Unit value.
Definition at line 881 of file ips2_display.c.
Referenced by ips2_draw_dashboard_environment(), ips2_draw_humidity_drop(), and ips2_draw_temperature_dynamic().
ips2_format_three_digits()
static void ips2_format_three_digits (char * text, uint32_t value) static
Format a value as three decimal digits.
Parameters
[in] text Null-terminated text string.
[in] value Value to process.
Definition at line 936 of file ips2_display.c.
Referenced by ips2_render_timer().
ips2_format_two_digits()
static void ips2_format_two_digits (char * text, uint32_t value) static
Format a value as two decimal digits.
Parameters
[in] text Null-terminated text string.
[in] value Value to process.
Definition at line 923 of file ips2_display.c.
Referenced by ips2_render_astronomy(), and ips2_render_timer().
ips2_glyph()
static const uint8_t * ips2_glyph (char character) static
Return the compact 5x7 bitmap for one supported character.
Parameters
[in] character Character to draw or look up.
Returns
Pointer to the requested register or data view.
Definition at line 465 of file ips2_display.c.
Referenced by ips2_draw_char(), and ips2_draw_text_opaque().
ips2_init()
int ips2_init (uint32_t pclka_hz)
Initialize the module.
Initialize IPS Display 2 Click over SCI0 simple SPI.
Parameters
[in] pclka_hz Peripheral clock A frequency in hertz.
Returns
Zero on success; otherwise a negative error code.
Definition at line 2274 of file ips2_display.c.
References ips2_bck_high(), ips2_bck_low(), IPS2_CMD_COLMOD, IPS2_CMD_DISPON, IPS2_CMD_FRCTR2, IPS2_CMD_GCTRL, IPS2_CMD_INVON, IPS2_CMD_MADCTL, IPS2_CMD_NVGAMCTRL, IPS2_CMD_PORCTRL, IPS2_CMD_PVGAMCTRL, IPS2_CMD_PWCTRL1, IPS2_CMD_SLPOUT, IPS2_CMD_VCOMS, IPS2_CMD_VDVSET, IPS2_CMD_VDVVRHEN, IPS2_CMD_VRHS, IPS2_COLOR_BG, ips2_configure_pins(), ips2_cs_high(), ips2_dc_high(), ips2_delay_ms(), ips2_fill_rect(), ips2_frame_drawn, IPS2_HEIGHT, ips2_rst_high(), ips2_rst_low(), ips2_spi_init(), IPS2_WIDTH, ips2_write_command(), and ips2_write_command_data().
Referenced by app_controller_init().
ips2_invalidate_screen()
void ips2_invalidate_screen (void)
Invalidate screen.
Invalidate UI caches so the next render redraws the complete screen.
Definition at line 699 of file ips2_display.c.
References ips2_animated_humidity_tenths, ips2_animated_temperature_tenths, ips2_frame_drawn, ips2_last_astronomy_mode, ips2_last_ble_connected, ips2_last_body_x, ips2_last_body_y, ips2_last_day, ips2_last_drawn_humidity_tenths, ips2_last_drawn_temperature_tenths, ips2_last_environment_valid, ips2_last_hour, ips2_last_humidity_tenths, ips2_last_minute, ips2_last_mode, ips2_last_month, ips2_last_second, ips2_last_temperature_tenths, ips2_last_timer_b3_action, ips2_last_timer_b4_action, ips2_last_timer_hour, ips2_last_timer_minute, ips2_last_timer_second, ips2_last_timer_state, ips2_last_weekday, and ips2_last_year.
Referenced by app_handle_ble_stopwatch_control(), app_handle_periodic_update(), and app_switch_screen().
ips2_isqrt()
static uint32_t ips2_isqrt (uint32_t value) static
Calculate the integer square root of an unsigned value.
Parameters
[in] value Value to process.
Returns
Calculated or converted value.
Definition at line 762 of file ips2_display.c.
Referenced by ips2_draw_filled_circle(), and ips2_draw_humidity_drop().
ips2_render_astronomy()
void ips2_render_astronomy (const rtc14_datetime_t * datetime, uint8_t ble_connected, uint32_t animation_ms)
Render astronomy.
Draw RTC time with the sun/moon Time of Day scene.
Parameters
[in] datetime Decoded RTC date and time.
[in] ble_connected Current BLE connection state.
[in] animation_ms Animation timebase in milliseconds.
Definition at line 1974 of file ips2_display.c.
References APP_SCREEN_ASTRONOMY, ips2_astronomy_arc_y(), ips2_clear_celestial_region(), IPS2_COLOR_CARD, IPS2_COLOR_WHITE, ips2_datetime_hour24(), ips2_draw_astronomy_arc(), ips2_draw_astronomy_static(), ips2_draw_celestial_body(), ips2_draw_horizon_silhouette(), ips2_draw_night_stars(), ips2_draw_text_opaque(), ips2_format_two_digits(), ips2_frame_drawn, ips2_last_astronomy_mode, ips2_last_body_x, ips2_last_body_y, ips2_last_hour, ips2_last_minute, ips2_last_second, ips2_render_ble_status(), ips2_render_error(), ips2_text_width(), IPS2_WIDTH, rtc14_datetime_t::minute, and rtc14_datetime_t::second.
Referenced by app_handle_periodic_update(), app_refresh_active_screen_if_due(), and app_render_active_screen().
ips2_render_ble_status()
void ips2_render_ble_status (uint8_t connected, app_screen_t screen)
Render ble status.
Refresh only the BLE icon on the selected screen.
Parameters
[in] connected BLE connection state or destination for that state.
[in] screen Application screen whose status area is being updated.
Definition at line 986 of file ips2_display.c.
References APP_SCREEN_DASHBOARD, APP_SCREEN_STOPWATCH, IPS2_COLOR_BG, IPS2_COLOR_CARD, IPS2_COLOR_CYAN, IPS2_COLOR_ERROR, IPS2_COLOR_MUTED, ips2_draw_bluetooth_symbol(), ips2_fill_rect(), and ips2_last_ble_connected.
Referenced by app_handle_ble_status(), ips2_render_astronomy(), ips2_render_dashboard(), ips2_render_environment(), ips2_render_error(), and ips2_render_timer().
ips2_render_dashboard()
void ips2_render_dashboard (const rtc14_datetime_t * datetime, const temphum27_data_t * environment, uint8_t ble_connected)
Render dashboard.
Draw the smartwatch dashboard with time, weekday, date and summaries.
Parameters
[in] datetime Decoded RTC date and time.
[in] environment Temperature and humidity measurement.
[in] ble_connected Current BLE connection state.
Definition at line 1279 of file ips2_display.c.
References APP_SCREEN_DASHBOARD, rtc14_datetime_t::day, ips2_draw_dashboard_date(), ips2_draw_dashboard_environment(), ips2_draw_dashboard_static(), ips2_draw_dashboard_time(), ips2_frame_drawn, ips2_last_day, ips2_last_month, ips2_last_weekday, ips2_last_year, ips2_render_ble_status(), ips2_render_error(), rtc14_datetime_t::month, rtc14_datetime_t::weekday, and rtc14_datetime_t::year.
Referenced by app_controller_init(), app_handle_periodic_update(), app_refresh_active_screen_if_due(), and app_render_active_screen().
ips2_render_environment()
void ips2_render_environment (const temphum27_data_t * environment, uint8_t ble_connected, uint32_t animation_ms)
Render environment.
Draw the animated temperature and humidity screen.
Parameters
[in] environment Temperature and humidity measurement.
[in] ble_connected Current BLE connection state.
[in] animation_ms Animation timebase in milliseconds.
Definition at line 1624 of file ips2_display.c.
References APP_SCREEN_ENVIRONMENT, temphum27_data_t::humidity_tenths_percent, ips2_animated_humidity_tenths, ips2_animated_temperature_tenths, ips2_approach_i16(), ips2_approach_u16(), ips2_draw_environment_static(), ips2_draw_humidity_drop(), ips2_draw_temperature_dynamic(), ips2_frame_drawn, ips2_last_drawn_humidity_tenths, ips2_last_drawn_temperature_tenths, ips2_last_environment_valid, ips2_last_humidity_tenths, ips2_last_temperature_tenths, ips2_render_ble_status(), temphum27_data_t::temperature_tenths_c, and temphum27_data_t::valid.
Referenced by app_handle_periodic_update(), app_refresh_active_screen_if_due(), and app_render_active_screen().
ips2_render_error()
void ips2_render_error (uint8_t ble_connected)
Render error.
Draw the RTC error screen while retaining BLE status.
Parameters
[in] ble_connected Current BLE connection state.
Definition at line 2250 of file ips2_display.c.
References APP_SCREEN_ASTRONOMY, IPS2_COLOR_BG, IPS2_COLOR_CARD, IPS2_COLOR_ERROR, IPS2_COLOR_MUTED, IPS2_COLOR_SOFT_WHITE, ips2_draw_frame(), ips2_draw_text_centered(), ips2_fill_rect(), ips2_frame_drawn, IPS2_HEIGHT, ips2_render_ble_status(), and IPS2_WIDTH.
Referenced by app_controller_init(), app_handle_periodic_update(), app_refresh_active_screen_if_due(), app_render_active_screen(), ips2_render_astronomy(), and ips2_render_dashboard().
ips2_render_timer()
void ips2_render_timer (uint32_t elapsed_ms, uint8_t running, uint8_t ble_connected)
Render timer.
Draw the stopwatch and its context-sensitive button actions.
Parameters
[in] elapsed_ms Stopwatch elapsed time in milliseconds.
[in] running Nonzero when the stopwatch is running.
[in] ble_connected Current BLE connection state.
Definition at line 2194 of file ips2_display.c.
References APP_SCREEN_STOPWATCH, IPS2_COLOR_BLUE, IPS2_COLOR_CARD, IPS2_COLOR_CARD_2, IPS2_COLOR_CYAN, IPS2_COLOR_DARK_CYAN, IPS2_COLOR_WHITE, ips2_draw_text_opaque(), ips2_draw_timer_actions(), ips2_draw_timer_state(), ips2_draw_timer_static(), ips2_fill_rect(), ips2_format_three_digits(), ips2_format_two_digits(), ips2_frame_drawn, ips2_last_timer_hour, ips2_last_timer_minute, ips2_last_timer_second, ips2_render_ble_status(), ips2_text_width(), and IPS2_WIDTH.
Referenced by app_handle_ble_stopwatch_control(), app_handle_physical_b3(), app_handle_physical_b4(), app_refresh_active_screen_if_due(), and app_render_active_screen().
ips2_rst_high()
static void ips2_rst_high (void) static
Deassert the display reset signal.
Definition at line 114 of file ips2_display.c.
References IPS2_RST_MASK.
Referenced by ips2_init().
ips2_rst_low()
static void ips2_rst_low (void) static
Assert the display reset signal.
Definition at line 108 of file ips2_display.c.
References IPS2_RST_MASK.
Referenced by ips2_init().
ips2_scene_color_at_y()
static uint16_t ips2_scene_color_at_y (uint8_t daylight, uint16_t y) static
Return the sky gradient color for a vertical scene coordinate.
Parameters
[in] daylight Nonzero for the daytime scene.
[in] y Vertical display coordinate.
Returns
Calculated or converted value.
Definition at line 1721 of file ips2_display.c.
References IPS2_COLOR_BG, IPS2_COLOR_HORIZON_DAY, IPS2_COLOR_HORIZON_NIGHT, IPS2_COLOR_SKY_DAY_LOW, IPS2_COLOR_SKY_DAY_MID, IPS2_COLOR_SKY_DAY_TOP, IPS2_COLOR_SKY_NIGHT_LOW, IPS2_COLOR_SKY_NIGHT_MID, and IPS2_COLOR_SKY_NIGHT_TOP.
Referenced by ips2_draw_celestial_body(), and ips2_fill_scene_rect().
ips2_sci0()
static volatile ra4m2_sci_registers_t * ips2_sci0 (void) static
Return the SCI0 register view used by IPS Display 2 Click.
Returns
Pointer to the requested register or data view.
Definition at line 87 of file ips2_display.c.
Referenced by ips2_sci0_set_speed(), ips2_spi_init(), ips2_spi_wait_complete(), and ips2_spi_write_byte().
ips2_sci0_set_speed()
static int ips2_sci0_set_speed (uint32_t pclka_hz, uint32_t speed_hz) static
Handle sci0 set speed.
Parameters
[in] pclka_hz Peripheral clock A frequency in hertz.
[in] speed_hz Requested serial clock frequency in hertz.
Returns
Calculated or converted value.
Definition at line 186 of file ips2_display.c.
References ra4m2_sci_registers_t::brr, ips2_sci0(), SCI_SEMR_BRME, ra4m2_sci_registers_t::semr, and ra4m2_sci_registers_t::smr.
Referenced by ips2_spi_init().
ips2_set_window()
static void ips2_set_window (uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1) static
Select the rectangular display RAM write window.
Parameters
[in] x0 Left display coordinate.
[in] y0 Top display coordinate.
[in] x1 Right display coordinate.
[in] y1 Bottom display coordinate.
Definition at line 367 of file ips2_display.c.
References IPS2_CMD_CASET, IPS2_CMD_RAMWR, IPS2_CMD_RASET, ips2_write_command(), and ips2_write_command_data().
Referenced by ips2_draw_humidity_drop(), ips2_draw_text_opaque(), and ips2_fill_rect().
ips2_spi_init()
static int ips2_spi_init (uint32_t pclka_hz) static
Handle spi init.
Parameters
[in] pclka_hz Peripheral clock A frequency in hertz.
Returns
Zero on success; otherwise a negative error code.
Definition at line 245 of file ips2_display.c.
References ra4m2_sci_registers_t::fcr, ips2_sci0(), ips2_sci0_set_speed(), IPS2_SPI_HZ, SCI_FCR_FM, SCI_SCMR_SDIR, SCI_SCMR_SINV, SCI_SCMR_SMIF, SCI_SCR_RE, SCI_SCR_TE, SCI_SIMR1_IICM, SCI_SMR_CM, SCI_SPMR_CKPH, SCI_SPMR_CKPOL, SCI_SSR_FER, SCI_SSR_ORER, SCI_SSR_PER, ra4m2_sci_registers_t::scmr, ra4m2_sci_registers_t::scr, ra4m2_sci_registers_t::simr1, ra4m2_sci_registers_t::smr, ra4m2_sci_registers_t::spmr, ra4m2_sci_registers_t::sptr, and ra4m2_sci_registers_t::ssr.
Referenced by ips2_init().
ips2_spi_wait_complete()
static void ips2_spi_wait_complete (void) static
Wait until the SCI0 transmission is complete.
Definition at line 310 of file ips2_display.c.
References ips2_sci0(), SCI_SSR_TEND, and ra4m2_sci_registers_t::ssr.
Referenced by ips2_draw_humidity_drop(), ips2_draw_text_opaque(), ips2_fill_rect(), ips2_write_command(), and ips2_write_command_data().
ips2_spi_write_byte()
static void ips2_spi_write_byte (uint8_t value) static
Transfer one byte over SCI0 simple SPI.
Parameters
[in] value Value to process.
Definition at line 282 of file ips2_display.c.
References ips2_sci0(), ra4m2_sci_registers_t::rdr, SCI_SSR_ORER, SCI_SSR_RDRF, SCI_SSR_TDRE, ra4m2_sci_registers_t::ssr, and ra4m2_sci_registers_t::tdr.
Referenced by ips2_draw_humidity_drop(), ips2_draw_text_opaque(), ips2_fill_rect(), ips2_write_command(), and ips2_write_command_data().
ips2_temperature_color()
static uint16_t ips2_temperature_color (int16_t temperature_tenths) static
Map a temperature value to an RGB565 cold-to-hot color.
Parameters
[in] temperature_tenths Temperature tenths value.
Returns
Calculated or converted value.
Definition at line 1318 of file ips2_display.c.
Referenced by ips2_draw_temperature_dynamic().
ips2_text_width()
static uint16_t ips2_text_width (const char * text, uint8_t scale) static
Calculate rendered text width for the selected font scale.
Parameters
[in] text Null-terminated text string.
[in] scale Integer font scale.
Returns
Calculated or converted value.
Definition at line 549 of file ips2_display.c.
Referenced by ips2_draw_dashboard_time(), ips2_draw_text_centered(), ips2_draw_text_in_rect_centered(), ips2_render_astronomy(), and ips2_render_timer().
ips2_write_command()
static void ips2_write_command (uint8_t command) static
Send one command byte to the display controller.
Parameters
[in] command CodeLess or display command string/value.
Definition at line 323 of file ips2_display.c.
References ips2_cs_high(), ips2_cs_low(), ips2_dc_low(), ips2_spi_wait_complete(), and ips2_spi_write_byte().
Referenced by ips2_init(), and ips2_set_window().
ips2_write_command_data()
static void ips2_write_command_data (uint8_t command, const uint8_t * data, uint32_t length) static
Send a display command followed by its data payload.
Parameters
[in] command CodeLess or display command string/value.
[in] data Data buffer.
[in] length Number of bytes in the buffer.
Definition at line 339 of file ips2_display.c.
References ips2_cs_high(), ips2_cs_low(), ips2_dc_high(), ips2_dc_low(), ips2_spi_wait_complete(), and ips2_spi_write_byte().
Referenced by ips2_init(), and ips2_set_window().
Variable Documentation
ips2_animated_humidity_tenths
uint16_t ips2_animated_humidity_tenths = 0xFFFFU static
Definition at line 77 of file ips2_display.c.
Referenced by ips2_invalidate_screen(), and ips2_render_environment().
ips2_animated_temperature_tenths
int16_t ips2_animated_temperature_tenths = (int16_t)0x7FFF static
Definition at line 76 of file ips2_display.c.
Referenced by ips2_invalidate_screen(), and ips2_render_environment().
ips2_frame_drawn
uint8_t ips2_frame_drawn static
Definition at line 56 of file ips2_display.c.
Referenced by ips2_init(), ips2_invalidate_screen(), ips2_render_astronomy(), ips2_render_dashboard(), ips2_render_environment(), ips2_render_error(), and ips2_render_timer().
ips2_last_astronomy_mode
uint8_t ips2_last_astronomy_mode = 0xFFU static
Definition at line 65 of file ips2_display.c.
Referenced by ips2_invalidate_screen(), and ips2_render_astronomy().
ips2_last_ble_connected
uint8_t ips2_last_ble_connected = 0xFFU static
Definition at line 75 of file ips2_display.c.
Referenced by ips2_invalidate_screen(), and ips2_render_ble_status().
ips2_last_body_x
uint16_t ips2_last_body_x = 0xFFFFU static
Definition at line 80 of file ips2_display.c.
Referenced by ips2_invalidate_screen(), and ips2_render_astronomy().
ips2_last_body_y
uint16_t ips2_last_body_y = 0xFFFFU static
Definition at line 81 of file ips2_display.c.
Referenced by ips2_invalidate_screen(), and ips2_render_astronomy().
ips2_last_day
uint8_t ips2_last_day = 0xFFU static
Definition at line 57 of file ips2_display.c.
Referenced by ips2_invalidate_screen(), and ips2_render_dashboard().
ips2_last_drawn_humidity_tenths
uint16_t ips2_last_drawn_humidity_tenths = 0xFFFFU static
Definition at line 79 of file ips2_display.c.
Referenced by ips2_invalidate_screen(), and ips2_render_environment().
ips2_last_drawn_temperature_tenths
int16_t ips2_last_drawn_temperature_tenths = (int16_t)0x7FFF static
Definition at line 78 of file ips2_display.c.
Referenced by ips2_invalidate_screen(), and ips2_render_environment().
ips2_last_environment_valid
uint8_t ips2_last_environment_valid = 0xFFU static
Definition at line 74 of file ips2_display.c.
Referenced by ips2_draw_dashboard_environment(), ips2_invalidate_screen(), and ips2_render_environment().
ips2_last_hour
uint8_t ips2_last_hour = 0xFFU static
Definition at line 61 of file ips2_display.c.
Referenced by ips2_draw_dashboard_time(), ips2_invalidate_screen(), and ips2_render_astronomy().
ips2_last_humidity_tenths
uint16_t ips2_last_humidity_tenths = 0xFFFFU static
Definition at line 73 of file ips2_display.c.
Referenced by ips2_draw_dashboard_environment(), ips2_invalidate_screen(), and ips2_render_environment().
ips2_last_minute
uint8_t ips2_last_minute = 0xFFU static
Definition at line 62 of file ips2_display.c.
Referenced by ips2_draw_dashboard_time(), ips2_invalidate_screen(), and ips2_render_astronomy().
ips2_last_mode
uint8_t ips2_last_mode = 0xFFU static
Definition at line 64 of file ips2_display.c.
Referenced by ips2_draw_dashboard_time(), and ips2_invalidate_screen().
ips2_last_month
uint8_t ips2_last_month = 0xFFU static
Definition at line 58 of file ips2_display.c.
Referenced by ips2_invalidate_screen(), and ips2_render_dashboard().
ips2_last_second
uint8_t ips2_last_second = 0xFFU static
Definition at line 63 of file ips2_display.c.
Referenced by ips2_invalidate_screen(), and ips2_render_astronomy().
ips2_last_temperature_tenths
int16_t ips2_last_temperature_tenths = (int16_t)0x7FFF static
Definition at line 72 of file ips2_display.c.
Referenced by ips2_draw_dashboard_environment(), ips2_invalidate_screen(), and ips2_render_environment().
ips2_last_timer_b3_action
uint8_t ips2_last_timer_b3_action = 0xFFU static
Definition at line 70 of file ips2_display.c.
Referenced by ips2_draw_timer_actions(), and ips2_invalidate_screen().
ips2_last_timer_b4_action
uint8_t ips2_last_timer_b4_action = 0xFFU static
Definition at line 71 of file ips2_display.c.
Referenced by ips2_draw_timer_actions(), and ips2_invalidate_screen().
ips2_last_timer_hour
uint8_t ips2_last_timer_hour = 0xFFU static
Definition at line 66 of file ips2_display.c.
Referenced by ips2_invalidate_screen(), and ips2_render_timer().
ips2_last_timer_minute
uint8_t ips2_last_timer_minute = 0xFFU static
Definition at line 67 of file ips2_display.c.
Referenced by ips2_invalidate_screen(), and ips2_render_timer().
ips2_last_timer_second
uint8_t ips2_last_timer_second = 0xFFU static
Definition at line 68 of file ips2_display.c.
Referenced by ips2_invalidate_screen(), and ips2_render_timer().
ips2_last_timer_state
uint8_t ips2_last_timer_state = 0xFFU static
Definition at line 69 of file ips2_display.c.
Referenced by ips2_draw_timer_state(), and ips2_invalidate_screen().
ips2_last_weekday
uint8_t ips2_last_weekday = 0xFFU static
Definition at line 60 of file ips2_display.c.
Referenced by ips2_invalidate_screen(), and ips2_render_dashboard().
ips2_last_year
uint8_t ips2_last_year = 0xFFU static
Definition at line 59 of file ips2_display.c.
Referenced by ips2_invalidate_screen(), and ips2_render_dashboard().