R7FA4M2 Multi-Click Smartwatch: include/ips2_display.h File Reference
ips2_display.h File Reference
IPS Display 2 transport and smartwatch UI rendering interface.
#include <stdint.h>
#include "app_types.h"
Functions
int ips2_init (uint32_t pclka_hz)
Initialize IPS Display 2 Click over SCI0 simple SPI.
void ips2_invalidate_screen (void)
Invalidate UI caches so the next render redraws the complete screen.
void ips2_render_dashboard (const rtc14_datetime_t *datetime, const temphum27_data_t *environment, uint8_t ble_connected)
Draw the smartwatch dashboard with time, weekday, date and summaries.
void ips2_render_environment (const temphum27_data_t *environment, uint8_t ble_connected, uint32_t animation_ms)
Draw the animated temperature and humidity screen.
void ips2_render_astronomy (const rtc14_datetime_t *datetime, uint8_t ble_connected, uint32_t animation_ms)
Draw RTC time with the sun/moon Time of Day scene.
void ips2_render_timer (uint32_t elapsed_ms, uint8_t running, uint8_t ble_connected)
Draw the stopwatch and its context-sensitive button actions.
void ips2_render_error (uint8_t ble_connected)
Draw the RTC error screen while retaining BLE status.
void ips2_render_ble_status (uint8_t connected, app_screen_t screen)
Refresh only the BLE icon on the selected screen.
Detailed Description
IPS Display 2 transport and smartwatch UI rendering interface.
Definition in file ips2_display.h.
Function Documentation
ips2_init()
int ips2_init (uint32_t pclka_hz)
Initialize IPS Display 2 Click over SCI0 simple SPI.
Parameters
[in] pclka_hz Peripheral clock A frequency in hertz.
Returns
Zero on success; otherwise a negative error code.
Initialize IPS Display 2 Click over SCI0 simple SPI.
Parameters
[in] pclka_hz Peripheral clock A frequency in hertz.
Returns
Zero on success; otherwise a negative error code.
Definition at line 2274 of file ips2_display.c.
References ips2_bck_high(), ips2_bck_low(), IPS2_CMD_COLMOD, IPS2_CMD_DISPON, IPS2_CMD_FRCTR2, IPS2_CMD_GCTRL, IPS2_CMD_INVON, IPS2_CMD_MADCTL, IPS2_CMD_NVGAMCTRL, IPS2_CMD_PORCTRL, IPS2_CMD_PVGAMCTRL, IPS2_CMD_PWCTRL1, IPS2_CMD_SLPOUT, IPS2_CMD_VCOMS, IPS2_CMD_VDVSET, IPS2_CMD_VDVVRHEN, IPS2_CMD_VRHS, IPS2_COLOR_BG, ips2_configure_pins(), ips2_cs_high(), ips2_dc_high(), ips2_delay_ms(), ips2_fill_rect(), ips2_frame_drawn, IPS2_HEIGHT, ips2_rst_high(), ips2_rst_low(), ips2_spi_init(), IPS2_WIDTH, ips2_write_command(), and ips2_write_command_data().
Referenced by app_controller_init().
ips2_invalidate_screen()
void ips2_invalidate_screen (void)
Invalidate UI caches so the next render redraws the complete screen.
Invalidate UI caches so the next render redraws the complete screen.
Definition at line 699 of file ips2_display.c.
References ips2_animated_humidity_tenths, ips2_animated_temperature_tenths, ips2_frame_drawn, ips2_last_astronomy_mode, ips2_last_ble_connected, ips2_last_body_x, ips2_last_body_y, ips2_last_day, ips2_last_drawn_humidity_tenths, ips2_last_drawn_temperature_tenths, ips2_last_environment_valid, ips2_last_hour, ips2_last_humidity_tenths, ips2_last_minute, ips2_last_mode, ips2_last_month, ips2_last_second, ips2_last_temperature_tenths, ips2_last_timer_b3_action, ips2_last_timer_b4_action, ips2_last_timer_hour, ips2_last_timer_minute, ips2_last_timer_second, ips2_last_timer_state, ips2_last_weekday, and ips2_last_year.
Referenced by app_handle_ble_stopwatch_control(), app_handle_periodic_update(), and app_switch_screen().
ips2_render_astronomy()
void ips2_render_astronomy (const rtc14_datetime_t * datetime, uint8_t ble_connected, uint32_t animation_ms)
Draw RTC time with the sun/moon Time of Day scene.
Parameters
[in] datetime Current decoded RTC date and time.
[in] ble_connected Current BLE connection state.
[in] animation_ms Application timebase in milliseconds.
Draw RTC time with the sun/moon Time of Day scene.
Parameters
[in] datetime Decoded RTC date and time.
[in] ble_connected Current BLE connection state.
[in] animation_ms Animation timebase in milliseconds.
Definition at line 1974 of file ips2_display.c.
References APP_SCREEN_ASTRONOMY, ips2_astronomy_arc_y(), ips2_clear_celestial_region(), IPS2_COLOR_CARD, IPS2_COLOR_WHITE, ips2_datetime_hour24(), ips2_draw_astronomy_arc(), ips2_draw_astronomy_static(), ips2_draw_celestial_body(), ips2_draw_horizon_silhouette(), ips2_draw_night_stars(), ips2_draw_text_opaque(), ips2_format_two_digits(), ips2_frame_drawn, ips2_last_astronomy_mode, ips2_last_body_x, ips2_last_body_y, ips2_last_hour, ips2_last_minute, ips2_last_second, ips2_render_ble_status(), ips2_render_error(), ips2_text_width(), IPS2_WIDTH, rtc14_datetime_t::minute, and rtc14_datetime_t::second.
Referenced by app_handle_periodic_update(), app_refresh_active_screen_if_due(), and app_render_active_screen().
ips2_render_ble_status()
void ips2_render_ble_status (uint8_t connected, app_screen_t screen)
Refresh only the BLE icon on the selected screen.
Parameters
[in] connected Current BLE connection state.
[in] screen Screen whose BLE status area should be refreshed.
Refresh only the BLE icon on the selected screen.
Parameters
[in] connected BLE connection state or destination for that state.
[in] screen Application screen whose status area is being updated.
Definition at line 986 of file ips2_display.c.
References APP_SCREEN_DASHBOARD, APP_SCREEN_STOPWATCH, IPS2_COLOR_BG, IPS2_COLOR_CARD, IPS2_COLOR_CYAN, IPS2_COLOR_ERROR, IPS2_COLOR_MUTED, ips2_draw_bluetooth_symbol(), ips2_fill_rect(), and ips2_last_ble_connected.
Referenced by app_handle_ble_status(), ips2_render_astronomy(), ips2_render_dashboard(), ips2_render_environment(), ips2_render_error(), and ips2_render_timer().
ips2_render_dashboard()
void ips2_render_dashboard (const rtc14_datetime_t * datetime, const temphum27_data_t * environment, uint8_t ble_connected)
Draw the smartwatch dashboard with time, weekday, date and summaries.
Parameters
[in] datetime Current decoded RTC date and time.
[in] environment Current temperature and humidity measurement.
[in] ble_connected Current BLE connection state.
Draw the smartwatch dashboard with time, weekday, date and summaries.
Parameters
[in] datetime Decoded RTC date and time.
[in] environment Temperature and humidity measurement.
[in] ble_connected Current BLE connection state.
Definition at line 1279 of file ips2_display.c.
References APP_SCREEN_DASHBOARD, rtc14_datetime_t::day, ips2_draw_dashboard_date(), ips2_draw_dashboard_environment(), ips2_draw_dashboard_static(), ips2_draw_dashboard_time(), ips2_frame_drawn, ips2_last_day, ips2_last_month, ips2_last_weekday, ips2_last_year, ips2_render_ble_status(), ips2_render_error(), rtc14_datetime_t::month, rtc14_datetime_t::weekday, and rtc14_datetime_t::year.
Referenced by app_controller_init(), app_handle_periodic_update(), app_refresh_active_screen_if_due(), and app_render_active_screen().
ips2_render_environment()
void ips2_render_environment (const temphum27_data_t * environment, uint8_t ble_connected, uint32_t animation_ms)
Draw the animated temperature and humidity screen.
Parameters
[in] environment Current temperature and humidity measurement.
[in] ble_connected Current BLE connection state.
[in] animation_ms Animation timebase in milliseconds.
Draw the animated temperature and humidity screen.
Parameters
[in] environment Temperature and humidity measurement.
[in] ble_connected Current BLE connection state.
[in] animation_ms Animation timebase in milliseconds.
Definition at line 1624 of file ips2_display.c.
References APP_SCREEN_ENVIRONMENT, temphum27_data_t::humidity_tenths_percent, ips2_animated_humidity_tenths, ips2_animated_temperature_tenths, ips2_approach_i16(), ips2_approach_u16(), ips2_draw_environment_static(), ips2_draw_humidity_drop(), ips2_draw_temperature_dynamic(), ips2_frame_drawn, ips2_last_drawn_humidity_tenths, ips2_last_drawn_temperature_tenths, ips2_last_environment_valid, ips2_last_humidity_tenths, ips2_last_temperature_tenths, ips2_render_ble_status(), temphum27_data_t::temperature_tenths_c, and temphum27_data_t::valid.
Referenced by app_handle_periodic_update(), app_refresh_active_screen_if_due(), and app_render_active_screen().
ips2_render_error()
void ips2_render_error (uint8_t ble_connected)
Draw the RTC error screen while retaining BLE status.
Parameters
[in] ble_connected Current BLE connection state.
Draw the RTC error screen while retaining BLE status.
Parameters
[in] ble_connected Current BLE connection state.
Definition at line 2250 of file ips2_display.c.
References APP_SCREEN_ASTRONOMY, IPS2_COLOR_BG, IPS2_COLOR_CARD, IPS2_COLOR_ERROR, IPS2_COLOR_MUTED, IPS2_COLOR_SOFT_WHITE, ips2_draw_frame(), ips2_draw_text_centered(), ips2_fill_rect(), ips2_frame_drawn, IPS2_HEIGHT, ips2_render_ble_status(), and IPS2_WIDTH.
Referenced by app_controller_init(), app_handle_periodic_update(), app_refresh_active_screen_if_due(), app_render_active_screen(), ips2_render_astronomy(), and ips2_render_dashboard().
ips2_render_timer()
void ips2_render_timer (uint32_t elapsed_ms, uint8_t running, uint8_t ble_connected)
Draw the stopwatch and its context-sensitive button actions.
Parameters
[in] elapsed_ms Stopwatch elapsed time in milliseconds.
[in] running Nonzero while the stopwatch is running.
[in] ble_connected Current BLE connection state.
Draw the stopwatch and its context-sensitive button actions.
Parameters
[in] elapsed_ms Stopwatch elapsed time in milliseconds.
[in] running Nonzero when the stopwatch is running.
[in] ble_connected Current BLE connection state.
Definition at line 2194 of file ips2_display.c.
References APP_SCREEN_STOPWATCH, IPS2_COLOR_BLUE, IPS2_COLOR_CARD, IPS2_COLOR_CARD_2, IPS2_COLOR_CYAN, IPS2_COLOR_DARK_CYAN, IPS2_COLOR_WHITE, ips2_draw_text_opaque(), ips2_draw_timer_actions(), ips2_draw_timer_state(), ips2_draw_timer_static(), ips2_fill_rect(), ips2_format_three_digits(), ips2_format_two_digits(), ips2_frame_drawn, ips2_last_timer_hour, ips2_last_timer_minute, ips2_last_timer_second, ips2_render_ble_status(), ips2_text_width(), and IPS2_WIDTH.
Referenced by app_handle_ble_stopwatch_control(), app_handle_physical_b3(), app_handle_physical_b4(), app_refresh_active_screen_if_due(), and app_render_active_screen().