R7FA4M2 Multi-Click Smartwatch: include/rtc14.h File Reference
rtc14.h File Reference
RTC 14 Click driver interface.
#include <stdint.h>
#include "app_types.h"
Functions
int rtc14_init (void)
Initialize the shared IIC0 transport used by RTC 14.
int rtc14_set_default_datetime (void)
Apply the example's configured default date and time.
int rtc14_set_datetime_24h (uint16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t minute, uint8_t second, uint8_t weekday)
Write a validated 24-hour date/time value to RTC 14.
int rtc14_get_datetime (rtc14_datetime_t *datetime)
Read a coherent RTC date/time snapshot.
void rtc14_print_datetime (const rtc14_datetime_t *datetime)
Print a decoded RTC value through printf_me().
Detailed Description
RTC 14 Click driver interface.
Definition in file rtc14.h.
Function Documentation
rtc14_get_datetime()
int rtc14_get_datetime (rtc14_datetime_t * datetime)
Read a coherent RTC date/time snapshot.
Parameters
[out] datetime Destination decoded date/time structure.
Returns
RTC14_OK on success; otherwise a negative application error code.
Read a coherent RTC date/time snapshot.
Parameters
[out] datetime Decoded RTC date and time.
Returns
Zero on success; otherwise a negative error code.
Definition at line 217 of file rtc14.c.
References rtc14_datetime_t::day, rtc14_datetime_t::hour, rtc14_datetime_t::is_24_hour, rtc14_datetime_t::is_pm, rtc14_datetime_t::minute, rtc14_datetime_t::month, rtc14_bcd_to_decimal(), RTC14_ERROR_ARGUMENT, RTC14_HOUR_12_MASK, RTC14_HOUR_24_MASK, RTC14_HOUR_FORMAT_24, RTC14_HOUR_PM, RTC14_OK, rtc14_read_registers(), RTC14_REG_SECONDS, rtc14_datetime_t::second, rtc14_datetime_t::weekday, and rtc14_datetime_t::year.
Referenced by app_controller_init(), and app_handle_periodic_update().
rtc14_init()
int rtc14_init (void)
Initialize the shared IIC0 transport used by RTC 14.
Returns
RTC14_OK on success; otherwise a negative application error code.
Initialize the shared IIC0 transport used by RTC 14.
Returns
Zero on success; otherwise a negative error code.
Definition at line 70 of file rtc14.c.
References iic0_bus_init(), and RTC14_OK.
Referenced by app_controller_init().
rtc14_print_datetime()
void rtc14_print_datetime (const rtc14_datetime_t * datetime)
Print a decoded RTC value through printf_me().
Parameters
[in] datetime Date/time value to print.
Print a decoded RTC value through printf_me().
Parameters
[in] datetime Decoded RTC date and time.
Definition at line 266 of file rtc14.c.
References rtc14_datetime_t::day, rtc14_datetime_t::hour, rtc14_datetime_t::is_24_hour, rtc14_datetime_t::is_pm, rtc14_datetime_t::minute, rtc14_datetime_t::month, printf_me(), rtc14_datetime_t::second, rtc14_datetime_t::weekday, and rtc14_datetime_t::year.
Referenced by app_controller_init(), and app_handle_periodic_update().
rtc14_set_datetime_24h()
int rtc14_set_datetime_24h (uint16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t minute, uint8_t second, uint8_t weekday)
Write a validated 24-hour date/time value to RTC 14.
Parameters
[in] year Full Gregorian year.
[in] month Month in the range 1 through 12.
[in] day Day of month.
[in] hour Hour in the range 0 through 23.
[in] minute Minute in the range 0 through 59.
[in] second Second in the range 0 through 59.
[in] weekday Weekday number, where zero is Sunday.
Returns
RTC14_OK on success; otherwise a negative application error code.
Write a validated 24-hour date/time value to RTC 14.
Parameters
[in] year Full year value.
[in] month Month in the range 1 through 12.
[in] day Day of month.
[in] hour Hour value.
[in] minute Minute value.
[in] second Second value.
[in] weekday Weekday number, where zero is Sunday.
Returns
Zero on success; otherwise a negative error code.
Definition at line 141 of file rtc14.c.
References iic0_bus_write(), rtc14_days_in_month(), rtc14_decimal_to_bcd(), RTC14_ERROR_ARGUMENT, RTC14_HOUR_FORMAT_12, RTC14_HOUR_PM, RTC14_I2C_ADDRESS, and RTC14_REG_SECONDS.
Referenced by bletiny_process_rtc_command(), and rtc14_set_default_datetime().
rtc14_set_default_datetime()
int rtc14_set_default_datetime (void)
Apply the example's configured default date and time.
Returns
RTC14_OK on success; otherwise a negative application error code.
Apply the example's configured default date and time.
Returns
Calculated or converted value.
Definition at line 200 of file rtc14.c.
References RTC14_DEFAULT_DAY, RTC14_DEFAULT_HOUR, RTC14_DEFAULT_MINUTE, RTC14_DEFAULT_MONTH, RTC14_DEFAULT_SECOND, RTC14_DEFAULT_WEEKDAY, RTC14_DEFAULT_YEAR, and rtc14_set_datetime_24h().
Referenced by app_controller_init().