R7FA4M2 Multi-Click Smartwatch: src/rtc14.c File Reference
rtc14.c File Reference
RTC 14 Click date/time validation, conversion and I2C access.
#include "rtc14.h"
#include "app_config.h"
#include "iic0_bus.h"
#include "project_platform.h"
Macros
#define RTC14_REG_SECONDS (0x00U)
#define RTC14_HOUR_FORMAT_12 (0x00U)
#define RTC14_HOUR_FORMAT_24 (0x80U)
#define RTC14_HOUR_PM (0x20U)
#define RTC14_HOUR_24_MASK (0x3FU)
#define RTC14_HOUR_12_MASK (0x1FU)
Functions
static uint8_t rtc14_bcd_to_decimal (uint8_t value)
Convert one packed BCD byte to decimal.
static uint8_t rtc14_decimal_to_bcd (uint8_t value)
Convert one decimal value to packed BCD.
static int rtc14_read_registers (uint8_t first_reg, uint8_t *data, uint32_t length)
Read a consecutive RTC register range through IIC0.
int rtc14_init (void)
Initialize the module.
static uint8_t rtc14_is_leap_year (uint16_t year)
Determine whether a full Gregorian year is a leap year.
static uint8_t rtc14_days_in_month (uint16_t year, uint8_t month)
Return the valid day count for a month and year.
int rtc14_set_datetime_24h (uint16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t minute, uint8_t second, uint8_t weekday)
Set datetime 24h.
int rtc14_set_default_datetime (void)
Set default datetime.
int rtc14_get_datetime (rtc14_datetime_t *datetime)
Read datetime.
void rtc14_print_datetime (const rtc14_datetime_t *datetime)
Print datetime.
Detailed Description
RTC 14 Click date/time validation, conversion and I2C access.
Definition in file rtc14.c.
Macro Definition Documentation
RTC14_HOUR_12_MASK
#define RTC14_HOUR_12_MASK (0x1FU)
Definition at line 16 of file rtc14.c.
RTC14_HOUR_24_MASK
#define RTC14_HOUR_24_MASK (0x3FU)
Definition at line 15 of file rtc14.c.
RTC14_HOUR_FORMAT_12
#define RTC14_HOUR_FORMAT_12 (0x00U)
Definition at line 12 of file rtc14.c.
RTC14_HOUR_FORMAT_24
#define RTC14_HOUR_FORMAT_24 (0x80U)
Definition at line 13 of file rtc14.c.
RTC14_HOUR_PM
#define RTC14_HOUR_PM (0x20U)
Definition at line 14 of file rtc14.c.
RTC14_REG_SECONDS
#define RTC14_REG_SECONDS (0x00U)
Definition at line 11 of file rtc14.c.
Function Documentation
rtc14_bcd_to_decimal()
static uint8_t rtc14_bcd_to_decimal (uint8_t value) static
Convert one packed BCD byte to decimal.
Parameters
[in] value Value to process.
Returns
Calculated or converted value.
Definition at line 27 of file rtc14.c.
Referenced by rtc14_get_datetime().
rtc14_days_in_month()
static uint8_t rtc14_days_in_month (uint16_t year, uint8_t month) static
Return the valid day count for a month and year.
Parameters
[in] year Full year value.
[in] month Month in the range 1 through 12.
Returns
Calculated or converted value.
Definition at line 108 of file rtc14.c.
References rtc14_is_leap_year().
Referenced by rtc14_set_datetime_24h().
rtc14_decimal_to_bcd()
static uint8_t rtc14_decimal_to_bcd (uint8_t value) static
Convert one decimal value to packed BCD.
Parameters
[in] value Value to process.
Returns
Calculated or converted value.
Definition at line 38 of file rtc14.c.
Referenced by rtc14_set_datetime_24h().
rtc14_get_datetime()
int rtc14_get_datetime (rtc14_datetime_t * datetime)
Read datetime.
Read a coherent RTC date/time snapshot.
Parameters
[out] datetime Decoded RTC date and time.
Returns
Zero on success; otherwise a negative error code.
Definition at line 217 of file rtc14.c.
References rtc14_datetime_t::day, rtc14_datetime_t::hour, rtc14_datetime_t::is_24_hour, rtc14_datetime_t::is_pm, rtc14_datetime_t::minute, rtc14_datetime_t::month, rtc14_bcd_to_decimal(), RTC14_ERROR_ARGUMENT, RTC14_HOUR_12_MASK, RTC14_HOUR_24_MASK, RTC14_HOUR_FORMAT_24, RTC14_HOUR_PM, RTC14_OK, rtc14_read_registers(), RTC14_REG_SECONDS, rtc14_datetime_t::second, rtc14_datetime_t::weekday, and rtc14_datetime_t::year.
Referenced by app_controller_init(), and app_handle_periodic_update().
rtc14_init()
int rtc14_init (void)
Initialize the module.
Initialize the shared IIC0 transport used by RTC 14.
Returns
Zero on success; otherwise a negative error code.
Definition at line 70 of file rtc14.c.
References iic0_bus_init(), and RTC14_OK.
Referenced by app_controller_init().
rtc14_is_leap_year()
static uint8_t rtc14_is_leap_year (uint16_t year) static
Determine whether a full Gregorian year is a leap year.
Parameters
[in] year Full year value.
Returns
Calculated or converted value.
Definition at line 88 of file rtc14.c.
Referenced by rtc14_days_in_month().
rtc14_print_datetime()
void rtc14_print_datetime (const rtc14_datetime_t * datetime)
Print datetime.
Print a decoded RTC value through printf_me().
Parameters
[in] datetime Decoded RTC date and time.
Definition at line 266 of file rtc14.c.
References rtc14_datetime_t::day, rtc14_datetime_t::hour, rtc14_datetime_t::is_24_hour, rtc14_datetime_t::is_pm, rtc14_datetime_t::minute, rtc14_datetime_t::month, printf_me(), rtc14_datetime_t::second, rtc14_datetime_t::weekday, and rtc14_datetime_t::year.
Referenced by app_controller_init(), and app_handle_periodic_update().
rtc14_read_registers()
static int rtc14_read_registers (uint8_t first_reg, uint8_t * data, uint32_t length) static
Read a consecutive RTC register range through IIC0.
Parameters
[in] first_reg First reg value.
[out] data Data buffer.
[in] length Number of bytes in the buffer.
Returns
Calculated or converted value.
Definition at line 51 of file rtc14.c.
References iic0_bus_read_after_restart(), iic0_bus_write(), RTC14_I2C_ADDRESS, and RTC14_OK.
Referenced by rtc14_get_datetime().
rtc14_set_datetime_24h()
int rtc14_set_datetime_24h (uint16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t minute, uint8_t second, uint8_t weekday)
Set datetime 24h.
Write a validated 24-hour date/time value to RTC 14.
Parameters
[in] year Full year value.
[in] month Month in the range 1 through 12.
[in] day Day of month.
[in] hour Hour value.
[in] minute Minute value.
[in] second Second value.
[in] weekday Weekday number, where zero is Sunday.
Returns
Zero on success; otherwise a negative error code.
Definition at line 141 of file rtc14.c.
References iic0_bus_write(), rtc14_days_in_month(), rtc14_decimal_to_bcd(), RTC14_ERROR_ARGUMENT, RTC14_HOUR_FORMAT_12, RTC14_HOUR_PM, RTC14_I2C_ADDRESS, and RTC14_REG_SECONDS.
Referenced by bletiny_process_rtc_command(), and rtc14_set_default_datetime().
rtc14_set_default_datetime()
int rtc14_set_default_datetime (void)
Set default datetime.
Apply the example's configured default date and time.
Returns
Calculated or converted value.
Definition at line 200 of file rtc14.c.
References RTC14_DEFAULT_DAY, RTC14_DEFAULT_HOUR, RTC14_DEFAULT_MINUTE, RTC14_DEFAULT_MONTH, RTC14_DEFAULT_SECOND, RTC14_DEFAULT_WEEKDAY, RTC14_DEFAULT_YEAR, and rtc14_set_datetime_24h().
Referenced by app_controller_init().