R7FA4M2 Multi-Click Smartwatch: include/temphum27.h File Reference
temphum27.h File Reference
Temp&Hum 27 Click driver interface.
#include "app_types.h"
Functions
void temphum27_init (void)
Configure, enable and reset Temp&Hum 27 Click.
int temphum27_read_data (temphum27_data_t *environment)
Read temperature and relative humidity with CRC validation.
void temphum27_print_data (const temphum27_data_t *environment)
Print a fixed-point environmental measurement through printf_me().
Detailed Description
Temp&Hum 27 Click driver interface.
Definition in file temphum27.h.
Function Documentation
temphum27_init()
void temphum27_init (void)
Configure, enable and reset Temp&Hum 27 Click.
Configure, enable and reset Temp&Hum 27 Click.
Definition at line 114 of file temphum27.c.
References temphum27_configure_pins(), and temphum27_reset().
Referenced by app_controller_init().
temphum27_print_data()
void temphum27_print_data (const temphum27_data_t * environment)
Print a fixed-point environmental measurement through printf_me().
Parameters
[in] environment Measurement to print.
Print a fixed-point environmental measurement through printf_me().
Parameters
[in] environment Temperature and humidity measurement.
Definition at line 205 of file temphum27.c.
References temphum27_data_t::humidity_tenths_percent, printf_me(), and temphum27_data_t::temperature_tenths_c.
Referenced by app_controller_init(), and app_handle_periodic_update().
temphum27_read_data()
int temphum27_read_data (temphum27_data_t * environment)
Read temperature and relative humidity with CRC validation.
Parameters
[out] environment Destination fixed-point environmental measurement.
Returns
RTC14_OK on success; otherwise a negative application error code.
Read temperature and relative humidity with CRC validation.
Parameters
[out] environment Temperature and humidity measurement.
Returns
Zero on success; otherwise a negative error code.
Definition at line 126 of file temphum27.c.
References temphum27_data_t::humidity_tenths_percent, iic0_bus_read_after_restart(), iic0_bus_write(), RTC14_ERROR_ARGUMENT, RTC14_OK, temphum27_data_t::temperature_tenths_c, temphum27_calculate_crc(), TEMPHUM27_CMD_HOLD_TEMP_HUM, TEMPHUM27_DATA_RESOLUTION, TEMPHUM27_ERROR_CRC, TEMPHUM27_HUM_SPAN_TENTHS, TEMPHUM27_I2C_ADDRESS, TEMPHUM27_TEMP_OFFSET_TENTHS, TEMPHUM27_TEMP_SPAN_TENTHS, and temphum27_data_t::valid.
Referenced by app_controller_init(), and app_handle_periodic_update().