R7FA4M2 Multi-Click Smartwatch: src/temphum27.c File Reference
temphum27.c File Reference
Temp&Hum 27 Click reset, CRC validation and fixed-point conversion.
#include "temphum27.h"
#include "app_config.h"
#include "iic0_bus.h"
#include "ra4m2_baremetal.h"
Macros
#define TEMPHUM27_EN_MASK (1U << 5) /* P105 */
#define TEMPHUM27_ALR_MASK (1U << 1) /* P101 */
Functions
static void temphum27_delay_ms (uint32_t milliseconds)
Delay for the requested number of milliseconds.
static void temphum27_configure_pins (void)
Configure pins.
static void temphum27_enable (void)
Enable the Temp&Hum 27 sensor through its GPIO pin.
static void temphum27_disable (void)
Disable the Temp&Hum 27 sensor through its GPIO pin.
static void temphum27_reset (void)
Reset the Temp&Hum 27 sensor and wait for startup.
static uint8_t temphum27_calculate_crc (const uint8_t *data, uint8_t length)
Calculate the sensor CRC for a two-byte measurement.
void temphum27_init (void)
Initialize the module.
int temphum27_read_data (temphum27_data_t *environment)
Read data.
void temphum27_print_data (const temphum27_data_t *environment)
Print data.
Detailed Description
Temp&Hum 27 Click reset, CRC validation and fixed-point conversion.
Definition in file temphum27.c.
Macro Definition Documentation
TEMPHUM27_ALR_MASK
#define TEMPHUM27_ALR_MASK (1U << 1) /* P101 */
Definition at line 12 of file temphum27.c.
TEMPHUM27_EN_MASK
#define TEMPHUM27_EN_MASK (1U << 5) /* P105 */
Definition at line 11 of file temphum27.c.
Function Documentation
temphum27_calculate_crc()
static uint8_t temphum27_calculate_crc (const uint8_t * data, uint8_t length) static
Calculate the sensor CRC for a two-byte measurement.
Parameters
[in] data Data buffer.
[in] length Number of bytes in the buffer.
Returns
Calculated or converted value.
Definition at line 84 of file temphum27.c.
Referenced by temphum27_read_data().
temphum27_configure_pins()
static void temphum27_configure_pins (void) static
Configure pins.
Definition at line 33 of file temphum27.c.
References PFS_PDR_OUTPUT.
Referenced by temphum27_init().
temphum27_delay_ms()
static void temphum27_delay_ms (uint32_t milliseconds) static
Delay for the requested number of milliseconds.
Parameters
[in] milliseconds Delay duration in milliseconds.
Definition at line 18 of file temphum27.c.
Referenced by temphum27_reset().
temphum27_disable()
static void temphum27_disable (void) static
Disable the Temp&Hum 27 sensor through its GPIO pin.
Definition at line 59 of file temphum27.c.
References TEMPHUM27_EN_MASK.
Referenced by temphum27_reset().
temphum27_enable()
static void temphum27_enable (void) static
Enable the Temp&Hum 27 sensor through its GPIO pin.
Definition at line 50 of file temphum27.c.
References TEMPHUM27_EN_MASK.
Referenced by temphum27_reset().
temphum27_init()
void temphum27_init (void)
Initialize the module.
Configure, enable and reset Temp&Hum 27 Click.
Definition at line 114 of file temphum27.c.
References temphum27_configure_pins(), and temphum27_reset().
Referenced by app_controller_init().
temphum27_print_data()
void temphum27_print_data (const temphum27_data_t * environment)
Print data.
Print a fixed-point environmental measurement through printf_me().
Parameters
[in] environment Temperature and humidity measurement.
Definition at line 205 of file temphum27.c.
References temphum27_data_t::humidity_tenths_percent, printf_me(), and temphum27_data_t::temperature_tenths_c.
Referenced by app_controller_init(), and app_handle_periodic_update().
temphum27_read_data()
int temphum27_read_data (temphum27_data_t * environment)
Read data.
Read temperature and relative humidity with CRC validation.
Parameters
[out] environment Temperature and humidity measurement.
Returns
Zero on success; otherwise a negative error code.
Definition at line 126 of file temphum27.c.
References temphum27_data_t::humidity_tenths_percent, iic0_bus_read_after_restart(), iic0_bus_write(), RTC14_ERROR_ARGUMENT, RTC14_OK, temphum27_data_t::temperature_tenths_c, temphum27_calculate_crc(), TEMPHUM27_CMD_HOLD_TEMP_HUM, TEMPHUM27_DATA_RESOLUTION, TEMPHUM27_ERROR_CRC, TEMPHUM27_HUM_SPAN_TENTHS, TEMPHUM27_I2C_ADDRESS, TEMPHUM27_TEMP_OFFSET_TENTHS, TEMPHUM27_TEMP_SPAN_TENTHS, and temphum27_data_t::valid.
Referenced by app_controller_init(), and app_handle_periodic_update().
temphum27_reset()
static void temphum27_reset (void) static
Reset the Temp&Hum 27 sensor and wait for startup.
Definition at line 68 of file temphum27.c.
References temphum27_delay_ms(), temphum27_disable(), and temphum27_enable().
Referenced by temphum27_init().