/**
 * @file iic0_bus.h
 * @brief Shared polling IIC0 master interface.
 */

#ifndef IIC0_BUS_H
#define IIC0_BUS_H

#include <stdint.h>

/**
 * @brief Initialize IIC0 on P400/P401 at the configured bus speed.
 * @return RTC14_OK on success; otherwise a negative application error code.
 */
int iic0_bus_init(void);

/**
 * @brief Write one transaction to a 7-bit I2C address.
 * @param[in] address 7-bit target address.
 * @param[in] data Source byte buffer.
 * @param[in] length Number of bytes to transmit.
 * @param[in] restart_after_write Nonzero to generate a repeated START instead of STOP.
 * @return RTC14_OK on success; otherwise a negative application error code.
 */
int iic0_bus_write(uint8_t address, const uint8_t *data, uint32_t length,
                   uint8_t restart_after_write);

/**
 * @brief Read bytes after a repeated START generated by the write phase.
 * @param[in] address 7-bit target address.
 * @param[out] data Destination byte buffer.
 * @param[in] length Number of bytes to receive.
 * @return RTC14_OK on success; otherwise a negative application error code.
 */
int iic0_bus_read_after_restart(uint8_t address, uint8_t *data,
                                uint32_t length);

#endif /* IIC0_BUS_H */
